import { useCallback, useEffect, useState } from "react";
import { call, ApiError, type ProblemDetails } from "../../api/client.js";
import { loadMe } from "../login/me.js";
import { yuan, days } from "./money.js";
import { usePending } from "../../api/pending.js";

/* ════════════════════════════════════════════════════════════════════
   工时台账。

   这一页要回答的问题不是"我这个月填了多少小时"，而是
   **「这条工时为什么算成这么多钱」** —— 给一个数字让人回头去问财务，
   等于这个系统在成本这一侧没有交付任何东西。

   所以有 `cost` 权限时，每条工时展开的是一条推导链：

       3.5 小时 ÷ 8 = 0.44 人天 × 费率卡人天单价 + 差旅 = 成本

   `dayCostCents` 是**提交当日生效的费率卡的快照**（I2）：
   费率卡明年调价，这条工时的成本不会变。这件事光看一个总数是看不出来的。

   而没有 `cost` 权限时 —— 种子里的 CRC 正是如此 ——
   成本那几列**整列消失**。界面明说"你填的工时折成多少钱，你看不到"，
   而不是留一排空单元格让人以为系统坏了。
   ════════════════════════════════════════════════════════════════════ */

interface Entry {
  id: string; studySiteId: string; siteCode: string;
  accountId: string; personName: string;
  workDate: string; workType: string; workTypeLabel: string;
  billable: boolean; hours: number;
  /* 成本三件套受 cost 列权限管辖：无权限时**字段不在**，不是 null */
  dayCostCents?: number; travelCents?: number; costCents?: number;
  rateCardId: string;
  subjectId: string | null; visitId: string | null;
  autoGenerated: boolean; note: string | null;
  voidedAt: string | null; voidedByName: string | null; voidReason: string | null;
  createdAt: string;
}
interface Site { id: string; code: string; hospital: string }
interface SideEffect { type: string; summary: string }

/** 与契约 WORK_TYPES 同源；中文名跟着后端下发的 workTypeLabel 走，
 *  这里只需要一个下拉的取值顺序。 */
const WORK_TYPES = ["visit_support", "sdv", "ethics", "monitoring",
  "ip_mgmt", "training", "bd", "rework"] as const;
const WORK_TYPE_LABEL: Record<string, string> = {
  visit_support: "受试者访视陪同", sdv: "源数据准备与核对",
  ethics: "伦理递交与跟进", monitoring: "现场监查（IMV）",
  ip_mgmt: "药品与物资管理", training: "内部培训",
  bd: "投标与商务支持", rework: "返工与整改"
};

const today = () => new Date().toISOString().slice(0, 10);
/** 人天 —— 与 calc 的 HOURS_PER_DAY 同一个数。
 *  这里只用于**显示推导过程**，成本本身由服务端算好下发。 */
const HOURS_PER_DAY = 8;

export function TimesheetPage() {
  const [rows, setRows] = useState<Entry[] | null>(null);
  const [sites, setSites] = useState<Site[]>([]);
  const [canWrite, setCanWrite] = useState<boolean | null>(null);
  const [includeVoided, setIncludeVoided] = useState(false);
  const [effects, setEffects] = useState<SideEffect[] | null>(null);
  const [problem, setProblem] = useState<ProblemDetails | null>(null);
  const [voiding, setVoiding] = useState<string | null>(null);
  const [reason, setReason] = useState("");
  const [busy, setBusy] = useState<string | null>(null);
  const [open, setOpen] = useState<string | null>(null);
  /* 作废是 L2 命令，断网时进发件箱 —— 那一行要说出来。
     **必须和别的 hook 排在一起**：放到下面 `if (!rows) return` 之后的话，
     两次渲染的 hook 数量就不一样了（React #310）—— 而它表现成整页白屏。 */
  const pending = usePending();

  const load = useCallback(async () => {
    const r = await call<{ items: Entry[] }>("listTimesheets",
      { query: { limit: 100, ...(includeVoided ? { includeVoided: true } : {}) } });
    setRows(r.items);
  }, [includeVoided]);

  useEffect(() => { void load(); }, [load]);
  useEffect(() => {
    void loadMe().then(m => setCanWrite(m.permissions.actions.includes("timeWrite")))
      .catch(() => setCanWrite(null));
    void call<{ items: Site[] }>("listStudySites", { query: { limit: 200 } })
      .then(r => setSites(r.items)).catch(() => setSites([]));
  }, []);

  if (!rows) return <p className="muted">加载中…</p>;

  /* 「有没有这一列」由**数据**决定，不由角色判断 —— 前端不重算权限。
     后端把无权限的字段删掉了，这里就少几列，仅此而已。 */
  const showCost = rows.some(r => r.costCents !== undefined);

  async function run(key: string, fn: () => Promise<{ sideEffects: SideEffect[] }>) {
    setBusy(key); setProblem(null);
    try {
      const r = await fn();
      setEffects(r.sideEffects.length ? r.sideEffects : null);
      await load();
    } catch (e) {
      if (e instanceof ApiError) { setProblem(e.problem); setEffects(null); }
      else throw e;
    } finally { setBusy(null); }
  }

  const voidEntry = (id: string) => run(id, async () => {
    const r = await call<{ sideEffects: SideEffect[] }>(
      "voidTimesheet", { params: { id }, body: { reason } });
    setVoiding(null); setReason("");
    return r;
  });

  return (
    <>
      <div className="page-head">
        <h2>工时台账</h2>
        <p>
          工时<b>不能删，只能作废</b> —— 「昨天的报表和今天不一样」是信任崩塌的开始。
        </p>
      </div>

      <div className="stack" style={{ maxWidth: 980 }}>
        {canWrite !== false && <FileTimesheet sites={sites} onDone={() => void load()} />}
        {canWrite === false && (
          <p className="muted" data-testid="no-time-write">
            填报工时需要「timeWrite」动作权限，你的角色没有 —— 这里只能查看。
          </p>
        )}

        {problem && (
          <div className="problem" data-testid="timesheet-problem">
            <strong>{problem.title}</strong><div>{problem.detail}</div>
          </div>
        )}
        {effects && (
          <ul className="effects" data-testid="timesheet-effects">
            {effects.map((e, i) => (
              <li key={i}><div className="t">{e.type}</div><div>{e.summary}</div></li>
            ))}
          </ul>
        )}

        <div className="row spread">
          <label className="row" style={{ gap: 6 }}>
            <input type="checkbox" checked={includeVoided} style={{ width: "auto" }}
              data-testid="include-voided"
              onChange={e => setIncludeVoided(e.target.checked)} />
            <span className="muted">显示已作废</span>
          </label>
          {!showCost && rows.length > 0 && (
            /* 留白会让人以为系统坏了；说清楚是权限，人才知道该找谁 */
            <span className="muted" data-testid="cost-hidden">
              成本那几列不在你的可见范围里 —— 你填的工时折成多少钱，由经营层看
            </span>
          )}
        </div>

        {rows.length === 0 && <p className="muted" data-testid="no-timesheet">还没有工时记录。</p>}

        <ul className="stack" style={{ listStyle: "none", margin: 0, padding: 0 }}>
          {rows.map(t => (
            <li key={t.id} className={`card stack ${t.voidedAt ? "voided" : ""}`}
              data-testid="timesheet-row">
              <div className="spread">
                <div>
                  <span className="mono">{t.workDate}</span>{" "}
                  <span className="mono">{t.siteCode}</span>{" "}
                  {t.workTypeLabel || WORK_TYPE_LABEL[t.workType] || t.workType}
                  <div className="muted">
                    {t.personName} · <b className="num">{t.hours}</b> 小时
                    {/* autoGenerated 做成角标而不是再写一句话：
                        自动生成的那条，服务端的 note 本来就是「由完成访视自动生成」，
                        再拼一遍会把同一句印两次。标记归标记，备注归备注。 */}
                    {t.note && ` · ${t.note}`}
                  </div>
                </div>
                <div className="row" style={{ gap: 6 }}>
                  {t.autoGenerated && (
                    <span className="chip flat" data-testid="auto-chip">自动</span>
                  )}
                  <span className={`chip ${t.billable ? "good" : "flat"}`}
                    data-testid="billable-chip">
                    {t.billable ? "可计费" : "不可计费"}
                  </span>
                  {showCost && t.costCents !== undefined && (
                    <span className="num" data-testid="cost-cell"
                      style={{ fontWeight: 600 }}>{yuan(t.costCents)}</span>
                  )}
                </div>
              </div>

              {/* 推导链：一个数字说不出它是怎么来的，这几行说得出 */}
              {showCost && t.costCents !== undefined && (
                <>
                  <button className="btn link" data-testid="why"
                    style={{ justifySelf: "start" }}
                    onClick={() => setOpen(open === t.id ? null : t.id)}>
                    {open === t.id ? "收起" : "这个数是怎么来的？"}
                  </button>
                  {open === t.id && (
                    <div className="derive" data-testid="derivation">
                      <div>
                        <b className="num">{t.hours}</b> 小时 ÷ {HOURS_PER_DAY}
                        {" = "}<b className="num">{days(t.hours / HOURS_PER_DAY)}</b> 人天
                      </div>
                      <div>
                        × 人天单价{" "}
                        <b className="num">{yuan(t.dayCostCents ?? 0)}</b>
                        {" "}<span className="muted">
                          （提交当日生效的费率卡快照，卡号 <span className="mono">
                            {t.rateCardId.slice(0, 8)}</span>）
                        </span>
                      </div>
                      {!!t.travelCents && (
                        <div>+ 差旅 <b className="num">{yuan(t.travelCents)}</b></div>
                      )}
                      <div className="tot">
                        = <b className="num">{yuan(t.costCents)}</b>
                      </div>
                      <p className="muted" style={{ margin: "6px 0 0" }}>
                        这是<b>提交时算出来的快照</b>：费率卡明年调价，这条工时的成本不会变。
                        改历史成本是没法向任何人解释的。
                      </p>
                    </div>
                  )}
                </>
              )}

              {t.voidedAt ? (
                <p className="muted" data-testid="void-note">
                  已由 {t.voidedByName ?? "—"} 作废 ——{t.voidReason}
                </p>
              ) : canWrite !== false && (
                <div>
                  {voiding === t.id ? (
                    <div className="stack" data-testid="void-form">
                      <label className="field">
                        <span>作废原因（必填，至少 4 字）—— 成本随即从统计里退出</span>
                        <input value={reason} data-testid="void-reason"
                          onChange={e => setReason(e.target.value)} />
                      </label>
                      <div className="row">
                        {pending("voidTimesheet", { id: t.id }) &&
                          <span className="chip flat" data-testid="queued-chip">待发</span>}
                        <button className="btn" data-testid="void-confirm"
                          disabled={reason.trim().length < 4 || busy === t.id}
                          onClick={() => void voidEntry(t.id)}>确认作废</button>
                        <button className="btn link"
                          onClick={() => setVoiding(null)}>取消</button>
                      </div>
                    </div>
                  ) : (
                    <button className="btn link" data-testid="void"
                      onClick={() => { setVoiding(t.id); setReason(""); }}>作废</button>
                  )}
                </div>
              )}
            </li>
          ))}
        </ul>
      </div>
    </>
  );
}

/* ── 填报 ─────────────────────────────────────────────────────────
   `billable` 不在表单里：它由工作类型推导，提交时落库固化（I1）。
   让人手选可计费，等于把一条会被核查追问的口径交给了当事人的心情。 */
function FileTimesheet({ sites, onDone }: { sites: Site[]; onDone: () => void }) {
  const [studySiteId, setSite] = useState("");
  const [workDate, setDate] = useState(today());
  const [workType, setType] = useState<string>("visit_support");
  const [hours, setHours] = useState("3.5");
  const [travel, setTravel] = useState("");
  const [note, setNote] = useState("");
  const [problem, setProblem] = useState<ProblemDetails | null>(null);
  const [busy, setBusy] = useState(false);

  async function submit() {
    setBusy(true); setProblem(null);
    try {
      await call("createTimesheet", { body: {
        studySiteId, workDate, workType, hours: Number(hours),
        ...(travel ? { travelCents: Math.round(Number(travel) * 100) } : {}),
        ...(note ? { note } : {})
      } });
      setNote(""); setTravel(""); onDone();
    } catch (e) {
      if (e instanceof ApiError) setProblem(e.problem); else throw e;
    } finally { setBusy(false); }
  }

  return (
    <section className="card stack" data-testid="file-timesheet">
      <h3>填报工时</h3>
      <div className="row" style={{ gap: 12, alignItems: "flex-end" }}>
        <label className="field" style={{ flex: "2 1 220px" }}>
          <span>中心</span>
          <select value={studySiteId} data-testid="ts-site"
            onChange={e => setSite(e.target.value)}>
            <option value="">请选择</option>
            {sites.map(s => (
              <option key={s.id} value={s.id}>{s.code} {s.hospital}</option>
            ))}
          </select>
        </label>
        <label className="field" style={{ flex: "1 1 150px" }}>
          <span>工作日期</span>
          <input type="date" value={workDate} max={today()} data-testid="ts-date"
            onChange={e => setDate(e.target.value)} />
        </label>
      </div>
      <div className="row" style={{ gap: 12, alignItems: "flex-end" }}>
        <label className="field" style={{ flex: "2 1 200px" }}>
          <span>工作类型（决定是否可计费，提交后固化）</span>
          <select value={workType} data-testid="ts-type"
            onChange={e => setType(e.target.value)}>
            {WORK_TYPES.map(w => (
              <option key={w} value={w}>{WORK_TYPE_LABEL[w]}</option>
            ))}
          </select>
        </label>
        <label className="field" style={{ flex: "1 1 110px" }}>
          <span>工时（小时）</span>
          <input type="number" step="0.25" min="0.25" max="24" value={hours}
            data-testid="ts-hours" onChange={e => setHours(e.target.value)} />
        </label>
        <label className="field" style={{ flex: "1 1 110px" }}>
          <span>差旅（元，选填）</span>
          <input type="number" step="1" min="0" value={travel}
            data-testid="ts-travel" onChange={e => setTravel(e.target.value)} />
        </label>
      </div>
      <label className="field">
        <span>备注（选填）</span>
        <input value={note} data-testid="ts-note" onChange={e => setNote(e.target.value)} />
      </label>

      {problem && (
        <div className="problem" data-testid="file-problem">
          <strong>{problem.title}</strong><div>{problem.detail}</div>
        </div>
      )}

      <div>
        <button className="btn primary" data-testid="ts-submit"
          disabled={busy || !studySiteId || Number(hours) < 0.25}
          onClick={() => void submit()}>{busy ? "提交中…" : "填报"}</button>
      </div>
    </section>
  );
}
