import { useEffect, useState } from "react";
import { call } from "../../api/client.js";

interface QualityEvent {
  id: string; code: string; siteCode: string; kind: string; severity: string;
  state: string; title: string; detail: string; autoGenerated: boolean;
  raisedBy: string; raisedOn: string; ageDays: number;
}

const SEV: Record<string, string> = { minor: "flat", major: "warn", critical: "crit" };

export function QualityPage() {
  const [items, setItems] = useState<QualityEvent[] | null>(null);
  useEffect(() => {
    call<{ items: QualityEvent[] }>("listQualityEvents", { query: { limit: 50 } })
      .then(r => setItems(r.items));
  }, []);

  return (
    <>
      <div className="page-head">
        <h2>质量台账</h2>
        <p>
          访视超窗会自动生成方案偏离，且与访视完成在同一个事务里 ——
          事后补录的偏离，核查时看的是补录时间，不是发生时间。
        </p>
      </div>
      {items?.length === 0 && (
        <p className="muted" data-testid="quality-empty">暂无质量事件。</p>
      )}
      <div className="stack">
        {items?.map(q => (
          <article key={q.id} className="card" data-testid="quality-item">
            <div className="spread">
              <div className="row">
                <span className="mono">{q.code}</span>
                <span className={`chip ${SEV[q.severity] ?? "flat"}`}>{q.severity}</span>
                {q.autoGenerated && <span className="chip flat">系统自动生成</span>}
              </div>
              <span className="muted mono">{q.raisedOn}</span>
            </div>
            <h3 style={{ margin: "8px 0 4px", fontSize: 14 }}>{q.title}</h3>
            <p className="muted" style={{ margin: 0 }}>{q.detail}</p>
          </article>
        ))}
      </div>
    </>
  );
}
