import { useEffect, useState } from "react";
import { call, ApiError, type ProblemDetails } from "../../api/client.js";
import { loadMe, type Me } from "../login/me.js";
import { SaePanel } from "./SaePanel.js";
import { IpPanel } from "./IpPanel.js";

interface QualityEvent {
  id: string; code: string; siteCode: string; kind: string; severity: string;
  state: string; title: string; detail: string; autoGenerated: boolean;
  raisedBy: string; raisedOn: string; ageDays: number;
  sourceEventId?: string | null;
  /* CAPA（迁移 0035）。**写措施的人不能自己验证关闭** ——
     这里是 capaWrite，验证关闭是 closeQA。 */
  category?: string | null;
  capaPlan?: string | null;
  capaOwnerName?: string | null;
  capaDueOn?: string | null;
  capaOverdueDays?: number | null;
  owesCapaPlan?: boolean;
}
interface Site { id: string; code: string; hospital: string }

const SEV: Record<string, string> = { minor: "flat", major: "warn", critical: "crit" };
const KIND: Record<string, string> = {
  deviation: "方案偏离", query: "数据质疑", ip_discrepancy: "药品不平衡",
  sae: "严重不良事件", sae_late: "SAE 超时上报", other: "其他"
};

export function QualityPage() {
  const [items, setItems] = useState<QualityEvent[] | null>(null);
  const [sites, setSites] = useState<Site[]>([]);
  /* 两本台账是**按中心**的（SAE 及时率、药品在手数量都没有跨中心的口径），
     所以这里要选一个中心。默认选第一个，而不是让人先点一下才有内容。 */
  const [siteId, setSiteId] = useState("");
  const [me, setMe] = useState<Me | null>(null);
  const [capaOn, setCapaOn] = useState<QualityEvent | null>(null);
  const [plan, setPlan] = useState("");
  const [dueOn, setDueOn] = useState("");
  const [busy, setBusy] = useState(false);
  const [problem, setProblem] = useState<ProblemDetails | null>(null);
  const [said, setSaid] = useState<string | null>(null);

  const reloadEvents = () =>
    call<{ items: QualityEvent[] }>("listQualityEvents", { query: { limit: 50 } })
      .then(r => setItems(r.items)).catch(() => setItems([]));

  useEffect(() => {
    void loadMe().then(setMe);
    void reloadEvents();
    void call<{ items: Site[] }>("listStudySites", { query: { limit: 200 } })
      .then(r => { setSites(r.items); setSiteId(s => s || r.items[0]?.id || ""); })
      .catch(() => setSites([]));
  }, []);

  const canCapa = me?.permissions.actions.includes("capaWrite") ?? false;

  const saveCapa = async () => {
    if (!capaOn) return;
    setBusy(true); setProblem(null); setSaid(null);
    try {
      const r = await call<{ sideEffects: { summary: string }[] }>("setCapaPlan", {
        params: { id: capaOn.id }, body: { plan: plan.trim(), dueOn }
      });
      await reloadEvents();
      setCapaOn(null);
      setSaid(r.sideEffects[0]?.summary ?? `${capaOn.code} 的整改措施已提交`);
    } catch (e) {
      if (e instanceof ApiError) setProblem(e.problem); else throw e;
    } finally { setBusy(false); }
  };

  return (
    <>
      <div className="page-head">
        <h2>质量台账</h2>
        <p>
          访视超窗会自动生成方案偏离，SAE 超过 24 小时上报会自动生成超时记录 ——
          两者都与触发它们的动作在<b>同一个事务里</b>写。
          事后补录的记录，核查时看的是补录时间，不是发生时间。
        </p>
      </div>

      {sites.length > 0 && (
        <label className="field" style={{ maxWidth: 380, marginBottom: 14 }}>
          <span>中心（SAE 及时率与药品台账按中心算）</span>
          <select value={siteId} data-testid="quality-site"
            onChange={e => setSiteId(e.target.value)}>
            {sites.map(s => (
              <option key={s.id} value={s.id}>{s.code} {s.hospital}</option>
            ))}
          </select>
        </label>
      )}

      {siteId && (
        <div className="stack" style={{ marginBottom: 18 }}>
          <SaePanel studySiteId={siteId} />
          <IpPanel studySiteId={siteId} />
        </div>
      )}

      {items?.length === 0 && (
        <p className="muted" data-testid="quality-empty">暂无质量事件。</p>
      )}
      <div className="stack">
        {items?.map(q => (
          <article key={q.id} className="card" data-testid="quality-item">
            <div className="spread">
              <div className="row">
                <span className="mono">{q.code}</span>
                <span className="chip flat">{KIND[q.kind] ?? q.kind}</span>
                <span className={`chip ${SEV[q.severity] ?? "flat"}`}>{q.severity}</span>
                {q.autoGenerated && <span className="chip flat">系统自动生成</span>}
              </div>
              <span className="muted mono">{q.raisedOn}</span>
            </div>
            <h3 style={{ margin: "8px 0 4px", fontSize: 14 }}>{q.title}</h3>
            <p className="muted" style={{ margin: 0 }}>{q.detail}</p>

            {/* ── CAPA ────────────────────────────────────────────────
                「已指派、还没写措施」是一个真实状态，不是「正在整改」——
                它是**有人欠着一份措施**，而这两件事要做的事完全不同。 */}
            {q.kind !== "query" && (
              <div style={{ marginTop: 8 }}>
                {q.capaPlan
                  ? <p className="muted" style={{ margin: 0, fontSize: 13 }}
                      data-testid="capa-plan">
                      <b>整改措施</b>（{q.capaOwnerName} · 期限 {q.capaDueOn}）：{q.capaPlan}
                      {(q.capaOverdueDays ?? 0) > 0 && (
                        <span className="chip crit" style={{ marginLeft: 6 }}
                          data-testid="capa-overdue">逾期 {q.capaOverdueDays} 天</span>
                      )}
                    </p>
                  : q.owesCapaPlan
                    ? <p style={{ margin: 0, fontSize: 13 }} data-testid="capa-owed">
                        <span className="chip crit">欠着整改措施</span>{" "}
                        已指派 <b>{q.capaOwnerName}</b>（期限 {q.capaDueOn}），
                        <b>但措施还没提交</b> —— 它不是「正在整改」。
                      </p>
                    : <p className="muted" style={{ margin: 0, fontSize: 13 }}>
                        还没有整改措施。
                      </p>}
                {canCapa && q.state !== "closed" && (
                  <button className="btn" style={{ marginTop: 6 }}
                    data-testid={`capa-edit-${q.id}`}
                    onClick={() => {
                      setCapaOn(q); setPlan(q.capaPlan ?? "");
                      setDueOn(q.capaDueOn ?? ""); setProblem(null);
                    }}>
                    {q.capaPlan ? "改整改措施" : "写整改措施"}
                  </button>
                )}
              </div>
            )}
          </article>
        ))}
      </div>

      {problem && (
        <div className="problem stack" data-testid="quality-problem" style={{ marginTop: 12 }}>
          <strong>{problem.title}</strong>
          {problem.detail && <div>{problem.detail}</div>}
        </div>
      )}
      {said && <p className="muted" data-testid="quality-said">{said}</p>}

      {capaOn && (
        <div className="card stack" data-testid="capa-form" style={{ marginTop: 16 }}>
          <h3>写 <span className="mono">{capaOn.code}</span> 的纠正与预防措施</h3>
          <label className="field">
            <span>措施</span>
            <textarea rows={3} value={plan} data-testid="capa-plan-input"
              placeholder="例：研究者集中补签并留痕（纠正）；把签名完整性做进 CRC 每周自查清单并留档（预防）。"
              onChange={e => setPlan(e.target.value)} />
          </label>
          <label className="field" style={{ maxWidth: 220 }}>
            <span>完成期限</span>
            <input type="date" value={dueOn} data-testid="capa-due-input"
              onChange={e => setDueOn(e.target.value)} />
          </label>
          <div className="derive" style={{ margin: 0 }}>
            <b>措施要写到「预防」那一层。</b>
            「集中补签并留痕」是纠正 —— 补完签名，下个月照样缺；
            预防是把签名完整性做进每周自查清单并留痕。
            <b>只做纠正不做预防的 CAPA，等于把同一个核查风险往后推了一个季度。</b>
            <br />
            <b>写措施的人不能自己验证关闭</b> —— 这一步是
            <span className="mono"> capaWrite</span>，验证关闭是
            <span className="mono"> closeQA</span>（QA 与机构办）。
          </div>
          <div className="row">
            <button className="btn primary" data-testid="capa-submit"
              disabled={busy || plan.trim().length < 10 || !dueOn}
              onClick={() => void saveCapa()}>{busy ? "…" : "提交措施"}</button>
            <button className="btn" onClick={() => setCapaOn(null)}>取消</button>
          </div>
        </div>
      )}
    </>
  );
}
