import { useEffect, useState } from "react";
import { call } from "../../api/client.js";
import { SaePanel } from "./SaePanel.js";
import { IpPanel } from "./IpPanel.js";

interface QualityEvent {
  id: string; code: string; siteCode: string; kind: string; severity: string;
  state: string; title: string; detail: string; autoGenerated: boolean;
  raisedBy: string; raisedOn: string; ageDays: number;
  sourceEventId?: string | null;
}
interface Site { id: string; code: string; hospital: string }

const SEV: Record<string, string> = { minor: "flat", major: "warn", critical: "crit" };
const KIND: Record<string, string> = {
  deviation: "方案偏离", query: "数据质疑", ip_discrepancy: "药品不平衡",
  sae: "严重不良事件", sae_late: "SAE 超时上报", other: "其他"
};

export function QualityPage() {
  const [items, setItems] = useState<QualityEvent[] | null>(null);
  const [sites, setSites] = useState<Site[]>([]);
  /* 两本台账是**按中心**的（SAE 及时率、药品在手数量都没有跨中心的口径），
     所以这里要选一个中心。默认选第一个，而不是让人先点一下才有内容。 */
  const [siteId, setSiteId] = useState("");

  useEffect(() => {
    call<{ items: QualityEvent[] }>("listQualityEvents", { query: { limit: 50 } })
      .then(r => setItems(r.items)).catch(() => setItems([]));
    call<{ items: Site[] }>("listStudySites", { query: { limit: 200 } })
      .then(r => { setSites(r.items); setSiteId(s => s || r.items[0]?.id || ""); })
      .catch(() => setSites([]));
  }, []);

  return (
    <>
      <div className="page-head">
        <h2>质量台账</h2>
        <p>
          访视超窗会自动生成方案偏离，SAE 超过 24 小时上报会自动生成超时记录 ——
          两者都与触发它们的动作在<b>同一个事务里</b>写。
          事后补录的记录，核查时看的是补录时间，不是发生时间。
        </p>
      </div>

      {sites.length > 0 && (
        <label className="field" style={{ maxWidth: 380, marginBottom: 14 }}>
          <span>中心（SAE 及时率与药品台账按中心算）</span>
          <select value={siteId} data-testid="quality-site"
            onChange={e => setSiteId(e.target.value)}>
            {sites.map(s => (
              <option key={s.id} value={s.id}>{s.code} {s.hospital}</option>
            ))}
          </select>
        </label>
      )}

      {siteId && (
        <div className="stack" style={{ marginBottom: 18 }}>
          <SaePanel studySiteId={siteId} />
          <IpPanel studySiteId={siteId} />
        </div>
      )}

      {items?.length === 0 && (
        <p className="muted" data-testid="quality-empty">暂无质量事件。</p>
      )}
      <div className="stack">
        {items?.map(q => (
          <article key={q.id} className="card" data-testid="quality-item">
            <div className="spread">
              <div className="row">
                <span className="mono">{q.code}</span>
                <span className="chip flat">{KIND[q.kind] ?? q.kind}</span>
                <span className={`chip ${SEV[q.severity] ?? "flat"}`}>{q.severity}</span>
                {q.autoGenerated && <span className="chip flat">系统自动生成</span>}
              </div>
              <span className="muted mono">{q.raisedOn}</span>
            </div>
            <h3 style={{ margin: "8px 0 4px", fontSize: 14 }}>{q.title}</h3>
            <p className="muted" style={{ margin: 0 }}>{q.detail}</p>
          </article>
        ))}
      </div>
    </>
  );
}
