import { z } from "zod";
import { Uuid, Code, DateOnly, Timestamp, Cents, CentsNonNeg, Ratio }
  from "../kernel/primitives.js";
import { gated } from "../kernel/fields.js";

/* ════════════════════════════════════════════════════════════════════
   Timesheet & Cost —— 钱这一侧。

   到 ClinicalOps 为止，系统知道「做了什么」，不知道「花了多少、赚了多少」。
   而这两个数字一旦开始骗人，整个看板就都不能信了。

   所有业务数字来自 `@sitedesk/calc`，且带口径版本号 —— 报表上要能标出
   「按哪版口径算的」。视图层不做算术。
   ════════════════════════════════════════════════════════════════════ */

export const WORK_TYPES = [
  "visit_support", "sdv", "ethics", "monitoring", "ip_mgmt",
  "training", "bd", "rework"
] as const;
export const WorkType = z.enum(WORK_TYPES).meta({
  id: "WorkType",
  description: "受试者访视陪同 / 源数据准备与核对 / 伦理递交与跟进 / 现场监查（IMV） / " +
    "药品与物资管理 / 内部培训 / 投标与商务支持 / 返工与整改"
});

export const RoleKindForRate = z.enum(["CRA", "CRC", "PM", "QA", "DM"])
  .meta({ id: "RoleKindForRate" });

export const RateCard = z.object({
  id: Uuid,
  roleKind: RoleKindForRate,
  level: z.string().nullable().describe("null 表示不分级别的通用行；精确级别优先匹配"),
  dayCostCents: gated(CentsNonNeg, "cost"),
  validFrom: DateOnly,
  validTo: DateOnly.nullable().describe("null = 至今"),
  note: z.string().nullable()
}).meta({
  id: "RateCard",
  description:
    "费率卡。**生效日期决定历史不被改写**（I2）——\n" +
    "只存一个常量的话，调价当天所有历史项目的毛利会集体变化，且无法向任何人解释。\n" +
    "同一工种/级别的生效区间不允许重叠，由数据库的 EXCLUDE 约束直接杜绝。"
});

export const TimesheetEntry = z.object({
  id: Uuid,
  studySiteId: Uuid,
  siteCode: Code,
  accountId: Uuid,
  personName: z.string(),
  workDate: DateOnly,
  workType: WorkType,
  workTypeLabel: z.string(),
  /** 落库固化（I1）：不随 work_type 的定义变更而改变 */
  billable: z.boolean()
    .describe("提交时按工作类型推导并**落库固化**。工作类型日后改了定义，历史工时不变。"),
  hours: z.number().min(0).max(24),
  /** 成本三件套受列权限管辖：一线填工时，但看不到自己值多少钱 */
  dayCostCents: gated(CentsNonNeg, "cost"),
  travelCents: gated(CentsNonNeg, "cost"),
  costCents: gated(CentsNonNeg, "cost"),
  rateCardId: Uuid,
  subjectId: Uuid.nullable(),
  visitId: Uuid.nullable(),
  autoGenerated: z.boolean().describe("由完成访视自动生成，非手工填报"),
  note: z.string().nullable(),
  voidedAt: Timestamp.nullable(),
  voidedByName: z.string().nullable(),
  voidReason: z.string().nullable(),
  createdAt: Timestamp,

  /* ── 审批（D4） ───────────────────────────────────────────────
     审批**不影响任何金额**：人已经干了活，成本已经发生。
     它只回答一个问题：**这笔工时有没有被第二个人看过。**

     不算进成本才是错的那条路 —— 毛利会比实际好看，
     等审批补上又突然掉一截，而那时没人说得清是经营变差了
     还是审批积压了。 */
  approvedAt: Timestamp.nullable(),
  approvedByName: z.string().nullable()
}).meta({
  id: "TimesheetEntry",
  description:
    "**工时不能删，只能作废。** 理由有两个，第二个更要紧：核查要求可追溯；" +
    "「昨天的报表和今天不一样」是信任崩塌的开始 —— " +
    "一旦一线发现报表会变，他们就不再照着它做决定了。"
});

/* ── 单中心 P&L ──────────────────────────────────────────────────── */

export const RevenueBreakdown = z.object({
  startupCents: gated(CentsNonNeg, "price"),
  enrollmentCents: gated(CentsNonNeg, "price"),
  dropoutDeductionCents: gated(Cents, "price").describe("负数。按已完成访视比例扣回"),
  screenFailFeeCents: gated(CentsNonNeg, "price"),
  revenueCents: gated(Cents, "price")
}).meta({
  id: "RevenueBreakdown",
  description:
    "I8'：收入 = 启动费 + 入组×单价 − 脱落未完成部分 + 筛败×单价×筛败费率。**四项缺一不可。**\n" +
    "两处修正方向相反：漏算筛败费会砍掉本来赚钱的高筛败中心；" +
    "漏算脱落扣减会保住实际在亏钱的高脱落中心。\n" +
    "**只做一个比两个都不做更危险 —— 因为它看起来是对的。**"
});

export const CostBreakdown = z.object({
  directCostCents: gated(CentsNonNeg, "cost"),
  billableCostCents: gated(CentsNonNeg, "cost"),
  nonBillableCostCents: gated(CentsNonNeg, "cost"),
  overheadCents: gated(CentsNonNeg, "cost"),
  totalCostCents: gated(CentsNonNeg, "cost"),
  /** 总成本里**还没被第二个人看过**的那一部分（D4）。
   *  它已经计入 totalCostCents —— 这一栏只说"其中有多少是待审的"。
   *  数字大而且一直不降，说明审批积压了，而不是成本失控。 */
  unapprovedCostCents: gated(CentsNonNeg, "cost"),
  personDays: gated(z.number(), "cost"),
  nonBillableShare: gated(Ratio, "cost")
    .describe("不可计费占比。它高，说明人力花在了卖不出去的事情上"),
  costPerEnrolledCents: gated(CentsNonNeg, "cost")
}).meta({ id: "CostBreakdown" });

export const SitePnl = z.object({
  studySiteId: Uuid,
  siteCode: Code,
  hospital: z.string(),
  state: z.string(),
  enrolled: z.int(), screenFailed: z.int(), withdrawn: z.int(),
  contracted: z.int(),
  revenue: RevenueBreakdown,
  cost: CostBreakdown,
  grossProfitCents: gated(Cents, "margin"),
  grossMargin: gated(z.number(), "margin")
    .describe("收入为 0 时不出现该字段 —— 「还没有收入」不等于「毛利率 0%」"),
  /** 口径版本号：报表要能标出「按哪版口径算的」 */
  calcVersion: z.string()
}).meta({
  id: "SitePnl",
  description:
    "单中心损益。所有数字来自 `@sitedesk/calc`，视图层不做算术。\n" +
    "三层列权限在这里同时生效：一线看得到中心，看不到价；\n" +
    "看得到自己填的工时，看不到它折成多少钱；毛利只有经营层看得到。"
});

/* ── 分月损益（欠账 D6） ────────────────────────────────────────────
   `SitePnl` 只有"到今天为止"的累计：看不出趋势，也回答不了
   「这个月比上个月差在哪」。而那正是经营层每个月要问的那一句。

   ── 分月的口径不是把累计除以月数 ──────────────────────────────────
   收入与成本都按**事件发生的那个月**归属：

     启动费      → SIV 当月（还没 SIV 就还没确认）
     入组收入    → 每一例的入组月
     筛败费      → 每一例的筛败月
     脱落扣减    → 每一例的退出月（负数）
     成本        → 工时的**工作日期**所在月，管理费按当月直接成本计提

   这不是唯一可能的口径，但它是**说得清**的那一种：
   每一笔钱都指得出"因为哪件事、在哪个月发生"。
   按录入时间归属会让补录的工时落在错误的月份，而那正是月度对不上的
   最常见来源。 */
export const PnlPeriod = z.object({
  /** `YYYY-MM` */
  month: z.string().regex(/^\d{4}-\d{2}$/),
  enrolled: z.int(), screenFailed: z.int(), withdrawn: z.int(),
  revenueCents: gated(Cents, "price"),
  costCents: gated(CentsNonNeg, "cost"),
  personDays: gated(z.number(), "cost"),
  grossProfitCents: gated(Cents, "margin")
}).meta({ id: "PnlPeriod" });

export const SitePnlTrend = z.object({
  studySiteId: Uuid,
  siteCode: Code,
  hospital: z.string(),
  months: z.array(PnlPeriod),
  calcVersion: z.string()
}).meta({
  id: "SitePnlTrend",
  description:
    "按月拆开的损益。每一笔钱按**事件发生的那个月**归属，不是按录入时间 —— " +
    "补录的工时落在错误的月份，是月度对不上最常见的来源。\n" +
    "把各月加起来不一定等于累计口径：累计里的脱落扣减是按**当前**访视完成度算的，" +
    "而它会随时间变化。两个数字回答的不是同一个问题。"
});
