import { Injectable } from "@nestjs/common";
import type { PoolClient } from "pg";
import {
  siteRevenue, siteCost, siteMargin, entryCostCents, CALC_VERSION,
  type Dropout, type CostEntry
} from "@sitedesk/calc";
import { ctx, principal } from "../../infra/ctx.js";
import { ProblemException, notFound } from "../../infra/problem.js";
import { AuditService } from "../../infra/audit.service.js";

/* ════════════════════════════════════════════════════════════════════
   Timesheet & Cost —— 服务层只做三件事：取数、调用 calc、写审计。

   **这里不出现任何算术。** 界面上的每个业务数字都来自 @sitedesk/calc，
   服务层再算一遍就等于有了第二套口径，而两套口径迟早会分叉 ——
   分叉那天，没人知道该信哪一个。
   ════════════════════════════════════════════════════════════════════ */

const day = (v: Date | null) => v ? v.toISOString().slice(0, 10) : null;

/** 丢掉值为 null 的键。受列权限管辖的字段一律非 nullable，
 *  「没有值」和「没有权限」用同一种表达：字段不出现。 */
const omitNull = <T extends Record<string, unknown>>(o: T): Partial<T> =>
  Object.fromEntries(Object.entries(o).filter(([, v]) => v !== null)) as Partial<T>;
const iso = (v: Date | null) => v ? v.toISOString() : null;

interface EntryRow {
  id: string; study_site_id: string; site_code: string; account_id: string;
  person_name: string; work_date: Date; work_type: string; work_type_label: string;
  billable: boolean; hours: string; day_cost_cents: string; travel_cents: string;
  cost_cents: string; rate_card_id: string; subject_id: string | null;
  visit_id: string | null; auto_generated: boolean; note: string | null;
  voided_at: Date | null; voided_by_name: string | null; void_reason: string | null;
  created_at: Date;
  approved_at: Date | null; approved_by_name: string | null;
}
const ENTRY_COLS = `
  t.id, t.study_site_id, s.code AS site_code, t.account_id, a.display_name AS person_name,
  t.work_date, t.work_type, w.label AS work_type_label, t.billable, t.hours,
  t.day_cost_cents, t.travel_cents, t.cost_cents, t.rate_card_id,
  t.subject_id, t.visit_id, t.auto_generated, t.note,
  t.voided_at, v.display_name AS voided_by_name, t.void_reason, t.created_at,
  t.approved_at, ap.display_name AS approved_by_name`;
const ENTRY_FROM = `
  timesheet_entry t
  JOIN study_site s ON s.id = t.study_site_id
  JOIN work_type w ON w.code = t.work_type
  JOIN account a ON a.id = t.account_id
  LEFT JOIN account v ON v.id = t.voided_by
  LEFT JOIN account ap ON ap.id = t.approved_by`;

const toEntry = (r: EntryRow) => ({
  id: r.id, studySiteId: r.study_site_id, siteCode: r.site_code,
  accountId: r.account_id, personName: r.person_name,
  workDate: day(r.work_date)!, workType: r.work_type, workTypeLabel: r.work_type_label,
  billable: r.billable, hours: Number(r.hours),
  dayCostCents: Number(r.day_cost_cents), travelCents: Number(r.travel_cents),
  costCents: Number(r.cost_cents), rateCardId: r.rate_card_id,
  subjectId: r.subject_id, visitId: r.visit_id, autoGenerated: r.auto_generated,
  note: r.note, voidedAt: iso(r.voided_at), voidedByName: r.voided_by_name,
  voidReason: r.void_reason, createdAt: iso(r.created_at)!,
  approvedAt: iso(r.approved_at), approvedByName: r.approved_by_name
});

/** 某人某天的工种与级别 —— 费率卡按这两项挑。 */
async function staffRate(client: PoolClient, accountId: string, on: string) {
  const { rows } = await client.query<{ role_kind: string | null; level: string | null }>(
    `SELECT st.role_kind, st.level FROM staff st WHERE st.account_id = $1`, [accountId]);
  /* 没有 staff 记录的账号（外部方）不该出现在这里；内部账号缺记录是数据问题，
     按角色兜底比拒绝填报更糟 —— 那会让一条成本悄悄用错费率。 */
  if (!rows[0]) return null;
  const { rows: card } = await client.query<{ id: string; day_cost_cents: string }>(
    `SELECT * FROM app.rate_on($1, $2, $3)`, [rows[0].role_kind, rows[0].level, on]);
  if (!card[0]) return null;
  return {
    roleKind: rows[0].role_kind!, level: rows[0].level,
    rateCardId: card[0].id, dayCostCents: Number(card[0].day_cost_cents)
  };
}

@Injectable()
export class CostService {
  constructor(private readonly audit: AuditService) {}

  /* ── 工时 ───────────────────────────────────────────────────────── */

  async listTimesheets(q: {
    limit: number; cursor?: string; studySiteId?: string; accountId?: string;
    workType?: string[]; from?: string; to?: string;
    includeVoided?: boolean; unapprovedOnly?: boolean;
  }) {
    const c = ctx();
    const params: unknown[] = [];
    const add = (v: unknown) => { params.push(v); return `$${params.length}`; };
    const conds = ["true"];
    if (q.studySiteId) conds.push(`t.study_site_id = ${add(q.studySiteId)}`);
    if (q.accountId) conds.push(`t.account_id = ${add(q.accountId)}`);
    if (q.workType?.length) conds.push(`t.work_type = ANY(${add(q.workType)})`);
    if (q.from) conds.push(`t.work_date >= ${add(q.from)}`);
    if (q.to) conds.push(`t.work_date <= ${add(q.to)}`);
    if (!q.includeVoided) conds.push(`t.voided_at IS NULL`);
    /* 已作废的不需要审 —— 它已经不在成本里了。所以"待审"天然排除作废。 */
    if (q.unapprovedOnly) conds.push(`t.approved_at IS NULL AND t.voided_at IS NULL`);
    if (q.cursor) conds.push(`t.id < ${add(q.cursor)}`);

    const { rows } = await c.client.query<EntryRow>(
      `SELECT ${ENTRY_COLS} FROM ${ENTRY_FROM} WHERE ${conds.join(" AND ")}
        ORDER BY t.work_date DESC, t.id DESC LIMIT ${add(q.limit + 1)}`, params);
    const items = rows.slice(0, q.limit).map(toEntry);
    return { items, nextCursor: rows.length > q.limit ? items.at(-1)?.id ?? null : null };
  }

  async createTimesheet(b: {
    studySiteId: string; workDate: string; workType: string; hours: number;
    travelCents?: number; subjectId?: string; note?: string;
  }) {
    const c = ctx(), p = principal();
    const site = await c.client.query<{ id: string; code: string }>(
      `SELECT id, code FROM study_site WHERE id = $1`, [b.studySiteId]);
    if (!site.rows[0]) throw notFound("中心");

    if (b.workDate > new Date().toISOString().slice(0, 10))
      throw new ProblemException("invariant-violated", {
        detail: "不能给未来的日期填报工时", invariant: "timesheet-not-future" });

    const rate = await staffRate(c.client, p.accountId, b.workDate);
    /* 找不到当日生效的费率卡时拒绝填报。用一个"差不多的"费率入账，
       比不入账更糟 —— 它会一直躺在报表里，没人发现。 */
    if (!rate) throw new ProblemException("invariant-violated", {
      detail: `找不到 ${b.workDate} 当日生效的费率卡（或该账号没有员工记录），无法计算成本`,
      invariant: "no-effective-rate-card" });

    /* billable 由工作类型推导，随后落库固化（I1） */
    const wt = await c.client.query<{ billable: boolean }>(
      `SELECT billable FROM work_type WHERE code = $1`, [b.workType]);
    if (!wt.rows[0]) throw notFound("工作类型");

    const travel = b.travelCents ?? 0;
    const cost = entryCostCents(b.hours, rate.dayCostCents, travel);

    const { rows } = await c.client.query<{ id: string }>(
      `INSERT INTO timesheet_entry (study_site_id, account_id, work_date, work_type,
         billable, hours, rate_card_id, day_cost_cents, travel_cents, cost_cents,
         subject_id, note)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING id`,
      [b.studySiteId, p.accountId, b.workDate, b.workType, wt.rows[0].billable,
       b.hours, rate.rateCardId, rate.dayCostCents, travel, cost,
       b.subjectId ?? null, b.note ?? null]);

    await this.audit.write({
      action: "填报工时", targetType: "timesheet_entry", targetId: site.rows[0].code,
      after: { workDate: b.workDate, workType: b.workType, hours: b.hours,
               costCents: cost, rateCardId: rate.rateCardId },
      studySiteId: b.studySiteId });
    return this.entry(rows[0]!.id);
  }

  private async entry(id: string) {
    const c = ctx();
    const { rows } = await c.client.query<EntryRow>(
      `SELECT ${ENTRY_COLS} FROM ${ENTRY_FROM} WHERE t.id = $1`, [id]);
    if (!rows[0]) throw notFound("工时");
    return toEntry(rows[0]);
  }

  /** 审批一条工时（欠账 D4）。
   *
   *  **它不改变任何金额。** 人已经干了活，成本已经发生 ——
   *  审批只回答一个问题：这笔工时有没有被第二个人看过。
   *
   *  不算进成本才是错的那条路：毛利会比实际好看，等审批补上又突然
   *  掉一截，而那时没人说得清是经营变差了还是审批积压了。 */
  async approveTimesheet(id: string, b: { note?: string }) {
    const c = ctx(), p = principal();
    const e = await this.entry(id);

    if (e.voidedAt) throw new ProblemException("invariant-violated", {
      detail: "这条工时已作废 —— 它已经不在成本里了，不需要审",
      invariant: "timesheet-voided-needs-no-approval" });
    if (e.approvedAt) throw new ProblemException("conflict-version", {
      detail: `这条工时已于 ${e.approvedAt} 由 ${e.approvedByName ?? "—"} 审过` });

    /* 审批的全部价值在于「第二个人」。自审等于没有审批流，
       只是多了一次点击 —— 而多出来的那次点击会让人以为这里已经有把关了。
       库里也有同名约束（timesheet_no_self_approve）：应用层会有第二个入口，
       而这条规则没有例外。 */
    if (e.accountId === p.accountId)
      throw new ProblemException("invariant-violated", {
        detail: "不能审自己填的工时 —— 审批的全部价值在于第二个人看过",
        invariant: "timesheet-no-self-approve" });

    await c.client.query(
      "UPDATE timesheet_entry SET approved_at = now(), approved_by = $2 WHERE id = $1",
      [id, p.accountId]);
    await this.audit.write({
      action: "审批工时", targetType: "timesheet_entry", targetId: id,
      before: { approvedAt: null }, after: { approvedAt: new Date().toISOString() },
      studySiteId: e.studySiteId, reason: b.note ?? null });

    return {
      data: await this.entry(id),
      sideEffects: [{
        type: "TimesheetApproved",
        summary: `${e.personName} ${e.workDate} 的 ${e.hours} 小时已审 —— ` +
          "**成本没有变化**：审批只是说这一笔被第二个人看过了",
        ref: id, studySiteId: e.studySiteId
      }]
    };
  }

  async voidTimesheet(id: string, b: { reason: string }) {
    const c = ctx(), p = principal();
    const e = await this.entry(id);
    if (e.voidedAt) throw new ProblemException("invariant-violated", {
      detail: "该条工时已作废", invariant: "timesheet-already-voided" });

    /* 只能作废自己填的；作废别人的要 approve 权限。
       这一条是行/列/动作三维之外的第四种判断：**是不是本人**。
       它没法用角色表达 —— 每个 CRC 都能作废自己的，谁也不能作废别人的。 */
    if (e.accountId !== p.accountId && !p.actions.includes("approve"))
      throw new ProblemException("invariant-violated", {
        detail: `这条工时是 ${e.personName} 填报的；作废他人的填报需要审批权限`,
        invariant: "void-own-or-approve" });

    await c.client.query(
      `UPDATE timesheet_entry SET voided_at = now(), voided_by = $2, void_reason = $3
        WHERE id = $1`, [id, p.accountId, b.reason]);
    await this.audit.write({
      action: "作废工时", targetType: "timesheet_entry", targetId: e.siteCode,
      before: { hours: e.hours, costCents: e.costCents },
      after: { voided: true }, reason: b.reason, studySiteId: e.studySiteId });

    return {
      data: await this.entry(id),
      sideEffects: [{
        type: "CostPosted",
        summary: `成本已冲回 ${((e.costCents ?? 0) / 100).toFixed(2)} 元 —— ` +
          "工时不删除，只作废；报表不会因此和昨天不一样",
        ref: id, amountCents: e.costCents ?? 0, studySiteId: e.studySiteId
      }]
    };
  }

  /* ── 费率卡 ─────────────────────────────────────────────────────── */

  async listRateCards(q: { limit: number; cursor?: string; roleKind?: string }) {
    const c = ctx();
    const params: unknown[] = [];
    const add = (v: unknown) => { params.push(v); return `$${params.length}`; };
    const conds = ["true"];
    if (q.roleKind) conds.push(`role_kind = ${add(q.roleKind)}`);
    if (q.cursor) conds.push(`id < ${add(q.cursor)}`);
    const { rows } = await c.client.query<{
      id: string; role_kind: string; level: string | null; day_cost_cents: string;
      valid_from: Date; valid_to: Date | null; note: string | null;
    }>(`SELECT id, role_kind, level, day_cost_cents, valid_from, valid_to, note
          FROM rate_card WHERE ${conds.join(" AND ")}
         ORDER BY role_kind, valid_from DESC LIMIT ${add(q.limit + 1)}`, params);
    const items = rows.slice(0, q.limit).map(r => ({
      id: r.id, roleKind: r.role_kind, level: r.level,
      dayCostCents: Number(r.day_cost_cents),
      validFrom: day(r.valid_from)!, validTo: day(r.valid_to), note: r.note
    }));
    return { items, nextCursor: rows.length > q.limit ? items.at(-1)?.id ?? null : null };
  }

  async createRateCard(b: {
    roleKind: string; level?: string | null; dayCostCents: number;
    validFrom: string; validTo?: string | null; note?: string;
  }) {
    const c = ctx();
    try {
      const { rows } = await c.client.query<{ id: string }>(
        `INSERT INTO rate_card (role_kind, level, day_cost_cents, valid_from, valid_to, note)
         VALUES ($1,$2,$3,$4,$5,$6) RETURNING id`,
        [b.roleKind, b.level ?? null, b.dayCostCents, b.validFrom, b.validTo ?? null,
         b.note ?? null]);
      await this.audit.write({
        action: "新增费率卡", targetType: "rate_card",
        targetId: `${b.roleKind}${b.level ? "/" + b.level : ""}`,
        after: { dayCostCents: b.dayCostCents, validFrom: b.validFrom } });
      const one = await this.listRateCards({ limit: 200, roleKind: b.roleKind });
      return one.items.find(x => x.id === rows[0]!.id)!;
    } catch (err) {
      /* 区间重叠是数据库层拒绝的 —— 这里只是把它翻译成说得清的话 */
      if (String(err).includes("rate_card_no_overlap"))
        throw new ProblemException("invariant-violated", {
          detail: `${b.roleKind} 在 ${b.validFrom} 起的区间与已有费率卡重叠 —— ` +
            "调价请给旧卡收口（设 validTo），再开新卡",
          invariant: "rate-card-overlap" });
      throw err;
    }
  }

  /** 给旧卡收口。**只能改 validTo，不能改单价** —— 改单价等于改写历史成本。 */
  async closeRateCard(id: string, b: { validTo: string }) {
    const c = ctx();
    const { rows } = await c.client.query<{
      id: string; role_kind: string; valid_from: Date; valid_to: Date | null;
    }>(`SELECT id, role_kind, valid_from, valid_to FROM rate_card WHERE id = $1`, [id]);
    if (!rows[0]) throw notFound("费率卡");
    const card = rows[0];
    if (card.valid_to)
      throw new ProblemException("invariant-violated", {
        detail: `该卡已收口于 ${day(card.valid_to)}`, invariant: "rate-card-already-closed" });
    if (b.validTo < day(card.valid_from)!)
      throw new ProblemException("invariant-violated", {
        detail: `收口日 ${b.validTo} 早于生效日 ${day(card.valid_from)}`,
        invariant: "rate-card-range" });

    /* valid_to 在 EXCLUDE 约束里是**右开区间**的上界：收口日当天仍生效，
       所以存的是次日。少存这一天，收口当天填的工时就找不到费率卡了。 */
    const exclusiveEnd = new Date(b.validTo);
    exclusiveEnd.setDate(exclusiveEnd.getDate() + 1);
    await c.client.query(`UPDATE rate_card SET valid_to = $2 WHERE id = $1`,
      [id, exclusiveEnd.toISOString().slice(0, 10)]);

    await this.audit.write({
      action: "费率卡收口", targetType: "rate_card", targetId: card.role_kind,
      before: { validTo: null }, after: { validTo: b.validTo } });
    const one = await this.listRateCards({ limit: 200, roleKind: card.role_kind });
    return { data: one.items.find(x => x.id === id)!, sideEffects: [] };
  }

  /* ── 分月损益（欠账 D6） ────────────────────────────────────────
     累计口径回答不了「这个月比上个月差在哪」，而那正是经营层每个月
     要问的那一句。每一笔钱按**事件发生的那个月**归属：

       启动费   → SIV 当月        入组收入 → 每一例的入组月
       筛败费   → 每一例的筛败月   脱落扣减 → 每一例的退出月
       成本     → 工时的**工作日期**所在月

     按录入时间归属会让补录的工时落在错误的月份 ——
     那是月度对不上最常见的来源。 */

  async sitePnlTrend(siteId: string, months = 12) {
    const c = ctx();
    const site = await c.client.query<{
      id: string; code: string; hospital: string; siv_on: Date | null;
      unit_price_cents: string; startup_fee_cents: string;
      screen_fail_fee_rate: string; overhead_rate: string; study_id: string;
    }>(`SELECT s.id, s.code, s.hospital, s.siv_on, s.unit_price_cents,
               s.startup_fee_cents, s.study_id,
               st.screen_fail_fee_rate, st.overhead_rate
          FROM study_site s JOIN study st ON st.id = s.study_id
         WHERE s.id = $1`, [siteId]);
    if (!site.rows[0]) throw notFound("中心");
    const s = site.rows[0];

    /* 受试者事件按月计数。三种事件三个日期字段，一条查询取回 ——
       分三条的话，"这一列到底数的是哪一批人"要靠读三段 SQL 才对得上。 */
    const ev = await c.client.query<{
      month: string; enrolled: string; screen_failed: string; withdrawn: string;
    }>(`
      WITH e AS (
        SELECT to_char(enrolled_on, 'YYYY-MM') AS month, 'enrolled' AS kind
          FROM subject WHERE study_site_id = $1 AND enrolled_on IS NOT NULL
        UNION ALL
        SELECT to_char(exited_on, 'YYYY-MM'), 'screen_failed'
          FROM subject WHERE study_site_id = $1 AND state = 'screen_failed'
            AND exited_on IS NOT NULL
        UNION ALL
        SELECT to_char(exited_on, 'YYYY-MM'), 'withdrawn'
          FROM subject WHERE study_site_id = $1 AND state = 'withdrawn'
            AND exited_on IS NOT NULL)
      SELECT month,
             count(*) FILTER (WHERE kind = 'enrolled')      AS enrolled,
             count(*) FILTER (WHERE kind = 'screen_failed') AS screen_failed,
             count(*) FILTER (WHERE kind = 'withdrawn')     AS withdrawn
        FROM e WHERE month IS NOT NULL GROUP BY month`, [siteId]);

    /* 脱落扣减要按**每一例**的访视完成度算，不能把比例平均了再乘 ——
       与累计口径同一条规矩（见 calc/revenue.ts）。 */
    const drops = await c.client.query<{ month: string; done: string; planned: string }>(
      `SELECT to_char(su.exited_on, 'YYYY-MM') AS month,
              (SELECT count(*) FROM subject_visit v
                WHERE v.subject_id = su.id AND v.status = 'locked') AS done,
              (SELECT count(*) FROM visit_template t WHERE t.study_id = $2) AS planned
         FROM subject su
        WHERE su.study_site_id = $1 AND su.state = 'withdrawn'
          AND su.exited_on IS NOT NULL`, [siteId, s.study_id]);

    const costs = await c.client.query<{
      month: string; cost_cents: string; billable: boolean; hours: string;
    }>(`SELECT to_char(work_date, 'YYYY-MM') AS month, cost_cents, billable, hours
          FROM timesheet_entry
         WHERE study_site_id = $1 AND voided_at IS NULL`, [siteId]);

    /* 月份轴：最近 N 个月（含当月）。**不是"有数据的那几个月"** ——
       中间空掉的月份必须画出来，"那个月一分钱收入都没有"正是要看见的事。 */
    const axis: string[] = [];
    const now = new Date();
    for (let i = months - 1; i >= 0; i--) {
      const d = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() - i, 1));
      axis.push(d.toISOString().slice(0, 7));
    }
    const sivMonth = s.siv_on ? s.siv_on.toISOString().slice(0, 7) : null;
    const unit = Number(s.unit_price_cents);

    const out = axis.map(month => {
      const e = ev.rows.find(r => r.month === month);
      const enrolled = Number(e?.enrolled ?? 0);
      const screenFailed = Number(e?.screen_failed ?? 0);
      const withdrawn = Number(e?.withdrawn ?? 0);

      const revenue = siteRevenue({
        /* 启动费只在 SIV 当月确认一次 —— 还没 SIV 就还没有这笔钱 */
        startupFeeCents: month === sivMonth ? Number(s.startup_fee_cents) : 0,
        unitPriceCents: unit,
        enrolled,
        screenFailed,
        screenFailFeeRate: Number(s.screen_fail_fee_rate),
        dropouts: drops.rows.filter(r => r.month === month).map(r => ({
          visitsDone: Number(r.done), visitsPlanned: Number(r.planned) }))
      });

      const entries: CostEntry[] = costs.rows.filter(r => r.month === month).map(r => ({
        costCents: Number(r.cost_cents), billable: r.billable,
        hours: Number(r.hours), voided: false }));
      const cost = siteCost(entries, Number(s.overhead_rate));

      return {
        month, enrolled, screenFailed, withdrawn,
        revenueCents: revenue.total,
        costCents: cost.totalCents,
        personDays: cost.personDays,
        grossProfitCents: revenue.total - cost.totalCents
      };
    });

    return {
      studySiteId: s.id, siteCode: s.code, hospital: s.hospital,
      months: out, calcVersion: CALC_VERSION
    };
  }

  /* ── 单中心损益 ─────────────────────────────────────────────────── */

  async sitePnl(siteId: string) {
    const c = ctx();
    const site = await c.client.query<{
      id: string; code: string; hospital: string; state: string; contracted: number;
      unit_price_cents: string; startup_fee_cents: string;
      screen_fail_fee_rate: string; overhead_rate: string;
    }>(`SELECT s.id, s.code, s.hospital, s.state, s.contracted,
               s.unit_price_cents, s.startup_fee_cents,
               st.screen_fail_fee_rate, st.overhead_rate
          FROM study_site s JOIN study st ON st.id = s.study_id
         WHERE s.id = $1`, [siteId]);
    if (!site.rows[0]) throw notFound("中心");
    const s = site.rows[0];

    /* 收入侧的输入：入组数、筛败数，以及每一例脱落的访视完成情况 */
    const counts = await c.client.query<{
      enrolled: string; screen_failed: string; withdrawn: string;
    }>(`SELECT count(*) FILTER (WHERE state IN ('enrolled','withdrawn','completed')) AS enrolled,
               count(*) FILTER (WHERE state = 'screen_failed')                       AS screen_failed,
               count(*) FILTER (WHERE state = 'withdrawn')                           AS withdrawn
          FROM subject WHERE study_site_id = $1`, [siteId]);
    const n = counts.rows[0]!;

    const drops = await c.client.query<{ done: string; planned: string }>(
      `SELECT (SELECT count(*) FROM subject_visit v
                WHERE v.subject_id = su.id AND v.status = 'locked')          AS done,
              (SELECT count(*) FROM visit_template t WHERE t.study_id = s.study_id) AS planned
         FROM subject su JOIN study_site s ON s.id = su.study_site_id
        WHERE su.study_site_id = $1 AND su.state = 'withdrawn'`, [siteId]);
    const dropouts: Dropout[] = drops.rows.map(r => ({
      visitsDone: Number(r.done), visitsPlanned: Number(r.planned) }));

    const revenue = siteRevenue({
      startupFeeCents: Number(s.startup_fee_cents),
      unitPriceCents: Number(s.unit_price_cents),
      enrolled: Number(n.enrolled),
      screenFailed: Number(n.screen_failed),
      screenFailFeeRate: Number(s.screen_fail_fee_rate),
      dropouts
    });

    /* 成本侧：未作废的工时。作废的由 SQL 直接排除，不在 JS 里过滤 —— 
       一条 WHERE 比一个 filter 更难被下一个人绕过去。 */
    const entries = await c.client.query<{
      cost_cents: string; billable: boolean; hours: string; approved: boolean;
    }>(`SELECT cost_cents, billable, hours, (approved_at IS NOT NULL) AS approved
          FROM timesheet_entry
         WHERE study_site_id = $1 AND voided_at IS NULL`, [siteId]);
    const costEntries: CostEntry[] = entries.rows.map(r => ({
      costCents: Number(r.cost_cents), billable: r.billable,
      hours: Number(r.hours), voided: false }));

    const cost = siteCost(costEntries, Number(s.overhead_rate));
    /* 待审的那一部分（D4）。它**已经计入 totalCostCents** ——
       这一栏只说"其中有多少还没被第二个人看过"。
       数字大而且一直不降，说明审批积压了，而不是成本失控。 */
    const unapprovedCostCents = entries.rows
      .filter(r => !r.approved)
      .reduce((n, r) => n + Number(r.cost_cents), 0);
    const margin = siteMargin(revenue.total, cost.totalCents, Number(n.enrolled));

    return {
      studySiteId: s.id, siteCode: s.code, hospital: s.hospital, state: s.state,
      enrolled: Number(n.enrolled), screenFailed: Number(n.screen_failed),
      withdrawn: Number(n.withdrawn), contracted: s.contracted,
      revenue: {
        startupCents: revenue.startup,
        enrollmentCents: revenue.enrollment,
        dropoutDeductionCents: revenue.dropoutDeduction,
        screenFailFeeCents: revenue.screenFailFee,
        revenueCents: revenue.total
      },
      cost: {
        directCostCents: cost.directCents,
        billableCostCents: cost.billableCents,
        nonBillableCostCents: cost.nonBillableCents,
        overheadCents: cost.overheadCents,
        totalCostCents: cost.totalCents,
        unapprovedCostCents,
        personDays: cost.personDays,
        /* 受列权限管辖的字段**不能同时可空**：null 会有两种含义
           （没权限 / 没有值），客户端分不清。所以「没有分母」时省略，
           与"无权限时消失"用同一种表达 —— 客户端只需要处理"它不在"。 */
        ...omitNull({
          nonBillableShare: cost.nonBillableShare,
          costPerEnrolledCents: margin.costPerEnrolledCents
        })
      },
      grossProfitCents: margin.grossProfitCents,
      ...omitNull({ grossMargin: margin.grossMargin }),
      calcVersion: CALC_VERSION
    };
  }

  /* ── 由完成访视自动生成工时（PostVisitTimesheet） ─────────────────
     这是 VisitCompleted 七个订阅者里的第六个。ClinicalOps 调用它，
     但**不 import 本模块的服务** —— 跨上下文只走这一个窄接口。 */
  async postVisitTimesheet(input: {
    studySiteId: string; visitId: string; subjectId: string;
    actualDate: string; hours: number;
  }): Promise<{ id: string; costCents: number } | null> {
    const c = ctx(), p = principal();
    const rate = await staffRate(c.client, p.accountId, input.actualDate);
    if (!rate) return null;          // 没有费率卡就不入账，由调用方在响应里说明

    const cost = entryCostCents(input.hours, rate.dayCostCents);
    const { rows } = await c.client.query<{ id: string }>(
      `INSERT INTO timesheet_entry (study_site_id, account_id, work_date, work_type,
         billable, hours, rate_card_id, day_cost_cents, cost_cents,
         subject_id, visit_id, auto_generated, note)
       VALUES ($1,$2,$3,'visit_support',true,$4,$5,$6,$7,$8,$9,true,$10)
       ON CONFLICT (visit_id, auto_generated) DO NOTHING RETURNING id`,
      [input.studySiteId, p.accountId, input.actualDate, input.hours,
       rate.rateCardId, rate.dayCostCents, cost, input.subjectId, input.visitId,
       "由完成访视自动生成"]);
    return rows[0] ? { id: rows[0].id, costCents: cost } : null;
  }
}
