/* ════════════════════════════════════════════════════════════════════
   一条业务流的 mock 场景 —— **有状态的，不是一堆固定响应。**

   契约生成的 examples.json 覆盖面全，但每个响应各自随机，
   拼不成一条连贯的流程：勾掉的任务下一次请求又是未勾的，
   完成访视后不会真的排出下一次。那种 mock 能验证「页面画得出来」，
   验证不了「这条流程走得通」—— 而后者才是 Phase 5 的退出标准。

   所以这里给**一份内存状态**，只覆盖 CRC 每天真正要走的那条路：
   看今天到期的 → 打开一例 → 逐项勾任务 → 完成访视 → 看到一串后果。

   数据取自原型（吴桐 / SS-01 北京协和 / S-0203），与种子同源。
   ════════════════════════════════════════════════════════════════════ */

import {
  DEFAULT_STARTUP_ITEMS, DEFAULT_HANDOVER_ITEMS, STARTUP_CATEGORY_LABEL
} from "@sitedesk/contracts";

export interface MockTask { seq: number; task: string; doneAt: string | null }

export interface MockStartupItem {
  id: string; studySiteId: string; category: string; categoryLabel: string;
  item: string; ownerAccountId: string | null; ownerName: string | null;
  dueOn: string | null; isBlocking: boolean;
  doneAt: string | null; doneByName: string | null; overdueDays: number | null;
}

/** 全量的 TimesheetEntry 形状 —— mock 少几个字段，界面就会在真库上才第一次报错。 */
export interface MockTimesheet {
  id: string; studySiteId: string; siteCode: string;
  accountId: string; personName: string;
  workDate: string; workType: string; workTypeLabel: string;
  billable: boolean; hours: number;
  dayCostCents: number; travelCents: number; costCents: number;
  rateCardId: string;
  subjectId: string | null; visitId: string | null;
  autoGenerated: boolean; note: string | null;
  voidedAt: string | null; voidedByName: string | null; voidReason: string | null;
  createdAt: string;
  /** 审批（D4）。**不影响任何金额** —— 只说这一笔被第二个人看过了。 */
  approvedAt: string | null; approvedByName: string | null;
}

export interface MockRateCard {
  id: string; roleKind: string; level: string | null;
  dayCostCents: number; validFrom: string; validTo: string | null;
  note: string | null;
}

export interface MockHandover {
  id: string; fromAccountId: string; fromName: string;
  toAccountId: string; toName: string; reason: string; plannedOn: string;
  status: string; completedAt: string | null;
  sites: { id: string; code: string; hospital: string }[];
  items: { seq: number; item: string; doneAt: string | null; doneByName: string | null }[];
}

export interface MockVisit {
  id: string; subjectId: string; screeningNo: string;
  studySiteId: string; siteCode: string; seq: number;
  visitCode: string; visitLabel: string;
  targetDate: string; windowDays: number; windowFrom: string; windowTo: string;
  actualDate: string | null; status: string; edcStatus: string;
  edcDaysLate: number | null; outOfWindow: boolean; daysLeft: number | null;
  piConfirmedAt: string | null; piConfirmedByName: string | null;
  tasks: MockTask[];
}

const iso = (d: Date) => d.toISOString().slice(0, 10);
const shift = (base: Date, n: number) => {
  const d = new Date(base); d.setDate(d.getDate() + n); return iso(d);
};
const TODAY = new Date();

/* 科室、城市、研究者都是**逐个中心**的。
   在此之前它们写死在 siteDto 里（三个中心同一个科室、同一个 PI、都在北京），
   于是「PI 只看自己签字的中心」这条行范围在 mock 上根本演不出来 ——
   三个中心的 pi_account_id 一样，PI 身份看到的就是全部。
   外部角色那四页的全部内容就是"看得窄"，看不窄等于那四页没测过。 */
const SITES = [
  { id: "s1", code: "SS-01", hospital: "北京协和医院", dept: "肝胆外科", city: "北京",
    piName: "陈国栋", piAccountId: "a-chenguod", state: "enrolling" },
  { id: "s2", code: "SS-07", hospital: "中山大学肿瘤防治中心", dept: "肿瘤内科", city: "广州",
    piName: "梁佩珊", piAccountId: null, state: "enrolling" },
  /* 第三个中心停在 contract —— 它存在的唯一理由是让 SIV 闸门有东西可拦。
     两个 enrolling 的中心谁也过不了闸门那一关，因为它们早就过去了。 */
  { id: "s3", code: "SS-14", hospital: "江苏省人民医院", dept: "呼吸与危重症医学科",
    city: "南京", piName: "邵建军", piAccountId: null, state: "contract" }
];

/** 每例的任务清单来自项目的 SOA —— 与 visit_template_task 同一套文字 */
const TASKS_ONCO = [
  "生命体征与体格检查",
  "血常规 + 生化采血（空腹）",
  "ECOG 体能评分记录",
  "研究药物发放与既往剩余回收清点",
  "合并用药与不良事件问询"
];
const TASKS_IO = [
  "生命体征与体格检查",
  "采血与样本离心送检（2 小时内）",
  "免疫相关不良事件专项问询",
  "研究药物配制核对与输注陪同"
];

function mkVisit(
  id: string, site: typeof SITES[number], screeningNo: string, subjectId: string,
  seq: number, label: string, dueIn: number, win: number, tasks: string[],
  doneCount = 0
): MockVisit {
  const target = shift(TODAY, dueIn);
  return {
    id, subjectId, screeningNo, studySiteId: site.id, siteCode: site.code, seq,
    visitCode: `V-${seq}`, visitLabel: label,
    targetDate: target, windowDays: win,
    windowFrom: shift(new Date(target), -win), windowTo: shift(new Date(target), win),
    actualDate: null, status: "planned", edcStatus: "pending",
    edcDaysLate: null, outOfWindow: dueIn + win < 0, daysLeft: dueIn + win,
    piConfirmedAt: null, piConfirmedByName: null,
    tasks: tasks.map((t, i) => ({
      seq: i, task: t, doneAt: i < doneCount ? new Date().toISOString() : null }))
  };
}

/** 把一条访视标成"已完成"。
 *  `outOfWindow` 在完成之后判的是**实际完成日在不在窗口内**，
 *  不再是"窗口关了还没做" —— 两种判法在 planned / done 上各管一段，
 *  写成一个 `dueIn + win < 0` 通吃的话，一条按时做完的历史访视
 *  会因为窗口早就过去而被标成超窗。 */
function done(v: MockVisit, doneIn: number): MockVisit {
  const actualDate = shift(TODAY, doneIn);
  return {
    ...v, actualDate, status: "done", daysLeft: null,
    outOfWindow: actualDate < v.windowFrom || actualDate > v.windowTo,
    tasks: v.tasks.map(t => ({ ...t, doneAt: new Date().toISOString() }))
  };
}

/** 可变状态。每次 resetScenario() 回到已知起点 —— 测试要从确定处出发。 */
export interface MockRole {
  id: string; code: string; name: string; isExternal: boolean; rowRule: string;
  visibleFields: string[]; allowedActions: string[]; modules: string[];
}
export interface MockTeam {
  id: string; code: string; name: string;
  lead: { id: string; displayName: string } | null;
  memberCount: number; studyCount: number;
}
export interface MockAccount {
  id: string; login: string; displayName: string;
  role: { id: string; code: string; name: string; isExternal: boolean };
  team: { id: string; code: string; name: string } | null;
  isExternal: boolean; orgRef: string | null;
  status: "active" | "disabled";
  joinedOn: string | null; disabledAt: string | null; disabledReason: string | null;
  lastLoginAt: string | null;
}

export interface Scenario {
  visits: MockVisit[];
  /* ── 组织与权限 ────────────────────────────────────────────────
     这三份是**可变的**：mock 模式下建号、改角色、勾权限都要当场看得见。
     取值与迁移 0026 的开户目录一致 —— 两处对不上的话，
     mock 上调通的界面到了真库会发现角色代号根本没有那一个。 */
  roles: MockRole[];
  teams: MockTeam[];
  accounts: MockAccount[];
  subjects: MockSubject[];
  payments: MockPayment[];
  submissions: MockSubmission[];
  /** 中心的当前阶段。推进会改它，所以不能从 SITES 常量上读。 */
  siteState: Record<string, string>;
  /** 计划 SIV 日 —— 清单项的到期日全是相对它算的，两处必须同源 */
  sivPlannedOn: string;
  /** 推进到 siv / enrolling 时回填，与后端的 `coalesce(siv_on, CURRENT_DATE)` 同义 */
  sivOn: Record<string, string>;
  fpiOn: Record<string, string>;
  startupItems: MockStartupItem[];
  handovers: MockHandover[];
  /** 完成访视时累积产生的质量事件，供台账页读取 */
  qualityEvents: {
    id: string; code: string; siteCode: string; kind: string; severity: string;
    state: string; title: string; detail: string; autoGenerated: boolean;
    raisedBy: string; raisedOn: string; ageDays: number;
    /* CAPA（迁移 0035）。**已指派但没写措施**是一个真实状态 ——
       它不是"正在整改"，是有人欠着一份措施。 */
    category?: string | null; capaPlan?: string | null;
    capaOwnerAccountId?: string | null; capaOwnerName?: string | null;
    capaDueOn?: string | null;
    /* SAE 三件套（I6）。只有 kind='sae' 的那几条有值。 */
    studySiteId?: string;
    occurredAt?: string | null; reportedAt?: string | null;
    sourceEventId?: string | null;
  }[];
  /** 数据质疑。**同一批行的另一个视角** —— 与 quality_event 里
   *  kind='query' 的那些是同一件东西，mock 里分开摆只是为了写得清楚。 */
  dataQueries: MockQuery[];
  /** 监查访视。四个日期各有各的问题，压成一个"状态"就答不出
   *  「为什么这个中心三个月没人管」。 */
  monitorVisits: MockMonitorVisit[];
  /** 内部稽查与发现项。机构质控是医院查我们，稽查是我们自己查自己。 */
  audits: MockAudit[];
  /** 药品流水（I5）。在手数量是**算出来的**，所以这里不存那个数。 */
  ipMovements: {
    id: string; studySiteId: string; movedOn: string; kind: string;
    quantity: number; subjectRef: string | null; refNo: string | null; note: string | null;
  }[];
  /** 生物样本。闭环 = 收到**或**销毁；两个都没有 = 在路上不知去向。 */
  specimens: {
    id: string; studySiteId: string; subjectRef: string; kind: string;
    collectedOn: string; shippedOn: string | null; receivedOn: string | null;
    discardedOn: string | null; trackingNo: string | null; closed: boolean;
  }[];
  timesheets: MockTimesheet[];
  rateCards: MockRateCard[];
  feasibility: MockFeas[];
  bids: MockBid[];
  changes: MockChange[];
  milestones: MockMilestone[];
}


/* 角色目录 —— 与迁移 0026 的开户目录逐条对应。
   照抄不是重复：两处对不上的话，mock 上调通的界面到了真库会发现
   角色代号根本没有那一个，而那种错在 e2e 上永远看不出来。 */
const ROLE_CATALOGUE: Omit<MockRole, "id">[] = [
  { code: "admin", name: "系统管理员", isExternal: false, rowRule: "all",
    visibleFields: ["cost", "margin", "price", "staff"],
    allowedActions: ["advance", "approve", "bid", "closeQ", "closeQA", "ethics", "manage",
      "piConfirm", "raiseQ", "rateWrite", "subjRead", "subjWrite", "timeWrite"],
    modules: ["org", "dash", "sites", "intake", "enr", "screen", "client", "cash",
      "feas", "price", "bid", "change", "staff", "people", "time", "pnl", "bill",
      "qa", "mon", "audit", "capa", "trail", "pm", "team", "approve", "cra", "mysites",
      "crc", "mysite", "sched", "subj", "query", "startup", "prescreen", "ethics",
      "handover", "isf", "material", "pay", "dm", "inst", "instac", "instqc",
      "instreg", "pi"] },
  { code: "boss", name: "经营层", isExternal: false, rowRule: "all",
    visibleFields: ["cost", "margin", "price", "staff"],
    allowedActions: ["advance", "approve", "bid", "manage", "rateWrite", "subjRead", "timeWrite"],
    modules: ["dash", "intake", "sites", "enr", "screen", "client", "cash", "bid", "change",
      "staff", "people", "time", "pnl", "bill", "qa", "mon", "price", "org", "trail"] },
  { code: "pm", name: "项目总监 PM", isExternal: false, rowRule: "team",
    visibleFields: ["cost", "margin", "price", "subject"],
    allowedActions: ["advance", "approve", "bid", "ethics", "raiseQ", "subjRead",
      "subjWrite", "timeWrite"],
    modules: ["pm", "team", "approve", "intake", "feas", "sites", "enr", "screen",
      "mon", "change", "qa", "pnl", "trail"] },
  { code: "cra", name: "临床监查员 CRA", isExternal: false, rowRule: "assigned",
    visibleFields: ["subject"], allowedActions: ["raiseQ", "subjRead", "timeWrite"],
    modules: ["cra", "mysites", "mon", "query", "screen", "feas", "material", "time",
      "qa", "capa", "trail"] },
  { code: "crc", name: "临床协调员 CRC", isExternal: false, rowRule: "assigned",
    visibleFields: ["subject"],
    allowedActions: ["ethics", "subjRead", "subjWrite", "timeWrite"],
    modules: ["crc", "mysite", "startup", "sched", "subj", "prescreen", "ethics",
      "query", "capa", "isf", "material", "pay", "handover", "time"] },
  { code: "dm", name: "数据管理 DM", isExternal: false, rowRule: "all",
    visibleFields: ["subject"], allowedActions: ["closeQ", "raiseQ", "subjRead"],
    modules: ["dm", "query", "screen", "trail"] },
  { code: "qa", name: "质量保证 QA", isExternal: false, rowRule: "all",
    visibleFields: ["subject"], allowedActions: ["closeQA", "raiseQ"],
    modules: ["audit", "qa", "screen", "mon", "trail"] },
  { code: "inst", name: "机构办（外部）", isExternal: true, rowRule: "hospital",
    visibleFields: ["subject"], allowedActions: ["closeQA"],
    modules: ["inst", "instac", "instqc", "instreg"] },
  { code: "pi", name: "研究者 PI（外部）", isExternal: true, rowRule: "pi",
    visibleFields: ["subject"], allowedActions: ["piConfirm", "subjRead"],
    modules: ["pi", "qa"] }
];

const mkRoles = (): MockRole[] =>
  ROLE_CATALOGUE.map(r => ({ id: `r-${r.code}`, ...r,
    visibleFields: [...r.visibleFields], allowedActions: [...r.allowedActions],
    modules: [...r.modules] }));

const mkTeams = (): MockTeam[] => [
  { id: "t1", code: "G-01", name: "华东华南组",
    lead: { id: "a-hanxue", displayName: "韩雪" }, memberCount: 0, studyCount: 2 },
  { id: "t2", code: "G-02", name: "华北西南组",
    lead: { id: "a-cendi", displayName: "岑迪" }, memberCount: 0, studyCount: 2 },
  { id: "t3", code: "G-00", name: "职能组", lead: null, memberCount: 0, studyCount: 0 }
];

const mkAccounts = (roles: MockRole[], teams: MockTeam[]): MockAccount[] => {
  const ref = (code: string) => {
    const r = roles.find(x => x.code === code)!;
    return { id: r.id, code: r.code, name: r.name, isExternal: r.isExternal };
  };
  const team = (code: string) => {
    const t = teams.find(x => x.code === code)!;
    return { id: t.id, code: t.code, name: t.name };
  };
  const mk = (login: string, displayName: string, role: string,
              opts: Partial<MockAccount> = {}): MockAccount => ({
    id: `a-${login}`, login, displayName, role: ref(role), team: null,
    isExternal: ref(role).isExternal, orgRef: null, status: "active",
    joinedOn: "2024-03-01", disabledAt: null, disabledReason: null,
    lastLoginAt: "2026-08-24T09:00:00.000Z", ...opts
  });
  return [
    mk("admin", "系统管理员", "admin", { joinedOn: "2026-08-01", lastLoginAt: null }),
    mk("lingyuan", "凌远", "boss", { team: team("G-00") }),
    mk("hanxue", "韩雪", "pm", { team: team("G-01") }),
    mk("cendi", "岑迪", "pm", { team: team("G-02") }),
    mk("linmin", "林敏", "cra", { team: team("G-01") }),
    mk("wutong", "吴桐", "crc", { team: team("G-01") }),
    mk("liaomeng", "廖萌", "crc", { team: team("G-02") }),
    mk("miaoqing", "苗青", "dm", { team: team("G-00") }),
    mk("weilan", "韦岚", "qa", { team: team("G-00") }),
    mk("zhanghm", "张慧敏", "inst", { orgRef: "北京协和医院" }),
    mk("chenguod", "陈国栋", "pi"),
    mk("zhouqi", "周琦", "cra", {
      status: "disabled", disabledAt: "2026-05-12T02:00:00.000Z",
      disabledReason: "离职，中心已交接给林敏" })
  ];
};

export function makeScenario(): Scenario {
  const roles = mkRoles();
  const teams = mkTeams();
  return {
    roles, teams, accounts: mkAccounts(roles, teams),
    subjects: mkSubjects(), payments: mkPayments(), submissions: mkSubmissions(),
    visits: [
      /* 已超窗 3 天 —— 列表第一屏就该看见它 */
      mkVisit("v1", SITES[0]!, "S-0331", "u1", 4, "C4D1 第 4 周期给药",
        -6, 3, TASKS_ONCO, 2),
      /* 今天到期 */
      mkVisit("v2", SITES[0]!, "S-0203", "u2", 8, "C8D1 第 8 周期给药",
        0, 3, TASKS_ONCO, 3),
      /* 窗口内，还有 2 天 */
      mkVisit("v3", SITES[1]!, "S-0224", "u3", 3, "C3D1 给药 + 肿瘤评估",
        2, 2, TASKS_IO, 0),
      /* 下周 */
      mkVisit("v4", SITES[1]!, "S-0198", "u4", 12, "C12D1 第 12 周期给药",
        7, 3, TASKS_IO, 0),
      /* ── 「我的日程」要的那一天 ──────────────────────────────────
         下面两条的窗口和 v3 重叠：中间那几天会同时落三次访视，
         而且分属两家医院。这一页存在的理由就是把那一天标出来 ——
         四条访视谁也撞不上谁的话，撞车那条分支在界面上永远不出现，
         也就没人会发现它其实没写对。 */
      mkVisit("v5", SITES[0]!, "S-0417", "u5", 6, "C6D1 给药 + 采血",
        2, 3, TASKS_ONCO, 0),
      mkVisit("v6", SITES[1]!, "S-0455", "u6", 2, "C2D1 给药",
        3, 3, TASKS_IO, 0),
      /* ── 研究者工作台要的那两条 ────────────────────────────────
         **做完了、但还没签字。** 六条 planned 的访视演不出这一页：
         PI 的整个工作面就是这个队列，队列空着，页面上
         "等了多久""超过 7 天"两条分支都不会出现。
         一条等了 12 天（该红），一条昨天做完的（正常）。 */
      done(mkVisit("v7", SITES[0]!, "S-0331", "u1", 5, "C5D1 第 5 周期给药",
        -12, 3, TASKS_ONCO), -12),
      done(mkVisit("v8", SITES[0]!, "S-0203", "u2", 9, "C9D1 第 9 周期给药",
        -1, 3, TASKS_ONCO), -1),
      /* 已经签过字的那条 —— 队列里**不该**出现它。
         少了这条对照，"pendingPi 到底筛没筛"在界面上看不出来。 */
      { ...done(mkVisit("v9", SITES[0]!, "S-0417", "u5", 3, "C3D1 给药",
          -20, 3, TASKS_ONCO), -20),
        piConfirmedAt: new Date(TODAY.getTime() - 18 * 86_400_000).toISOString(),
        piConfirmedByName: "陈国栋" }
    ],
    /* 演示数据里**故意各摆一条**：一条按时上报、一条超时未报。
       只摆按时的那种，界面上那两个"最坏的一条""还在计时"永远画不出来，
       于是没有人会发现它们其实没写对。 */
    qualityEvents: [...makeSaes(), ...makeQualityEvents()],
    dataQueries: makeDataQueries(),
    monitorVisits: makeMonitorVisits(),
    audits: makeAudits(),
    ipMovements: makeIpMovements(),
    specimens: makeSpecimens(),
    timesheets: makeTimesheets(),
    rateCards: makeRateCards(),
    feasibility: mkFeas(),
    bids: mkBids(),
    changes: mkChanges(),
    milestones: mkMilestones(),
    siteState: Object.fromEntries(SITES.map(s => [s.id, s.state])),
    sivPlannedOn: SIV_PLANNED,
    sivOn: {}, fpiOn: {},
    startupItems: makeStartupItems("s3"),
    handovers: [makeHandover()]
  };
}

/** 启动清单由**契约里的标准清单**铺开，不另写一份。
 *  另写一份的代价不是重复，是分歧：真实建档铺 16 项、mock 铺 6 项，
 *  于是 mock 上走得通的流程在真库上多出十项没人见过的阻塞。 */
const SIV_PLANNED = shift(TODAY, 20);

function makeStartupItems(siteId: string): MockStartupItem[] {
  return DEFAULT_STARTUP_ITEMS.map((d, i) => {
    const due = shift(new Date(SIV_PLANNED), d.dueOffset);
    const overdue = Math.round(
      (TODAY.getTime() - new Date(due).getTime()) / 86_400_000);
    return {
      id: `si-${i}`, studySiteId: siteId,
      category: d.category, categoryLabel: STARTUP_CATEGORY_LABEL[d.category],
      item: d.item, ownerAccountId: "a-wutong", ownerName: "吴桐",
      dueOn: due, isBlocking: d.blocking,
      doneAt: null, doneByName: null,
      overdueDays: overdue > 0 ? overdue : null
    };
  });
}

function makeHandover(): MockHandover {
  return {
    id: "h1", fromAccountId: "a-wutong", fromName: "吴桐",
    toAccountId: "a-tangyan", toName: "唐延",
    reason: "产假，为期六个月", plannedOn: shift(TODAY, 7),
    status: "pending", completedAt: null,
    sites: [{ id: "s1", code: "SS-01", hospital: "北京协和医院" }],
    items: DEFAULT_HANDOVER_ITEMS.map((item, seq) => ({
      seq, item, doneAt: null, doneByName: null
    }))
  };
}

/** mock 人员名册。发起交接的表单要靠它把候选人缩到同工种。 */
/* GCP 与在职状态是「派工与产能」那一页的正题，所以 mock 里要造得出
   三种状态：已过期、快到期、还早。全填 null 的话那一页在 mock 上
   永远是一片"未登记"，而它要盯的两件事一件都看不见。 */
const gcp = (daysLeft: number | null) => daysLeft === null
  ? { gcpExpiresOn: null, gcpDaysLeft: null }
  : {
      gcpExpiresOn: new Date(Date.now() + daysLeft * 86_400_000).toISOString().slice(0, 10),
      gcpDaysLeft: daysLeft
    };

export const STAFF_LIST = [
  { accountId: "a-wutong",  login: "wutong",  displayName: "吴桐", roleKind: "CRC",
    level: "P4", city: "北京", ...gcp(410),
    mentorName: null, successorName: "唐延", siteCount: 2, successionGap: false,
    active: true, disabledReason: null },
  { accountId: "a-tangyan", login: "tangyan", displayName: "唐延", roleKind: "CRC",
    level: "P3", city: "西安", ...gcp(45),
    mentorName: "吴桐", successorName: null, siteCount: 1, successionGap: false,
    active: true, disabledReason: null },
  { accountId: "a-duan",    login: "duanzhiyu", displayName: "段志远", roleKind: "CRA",
    level: "P5", city: "上海", ...gcp(-12),
    mentorName: null, successorName: null, siteCount: 4, successionGap: true,
    active: true, disabledReason: null },
  { accountId: "a-zhouqi",  login: "zhouqi", displayName: "周琦", roleKind: "CRA",
    level: "P4", city: "广州", ...gcp(120),
    mentorName: null, successorName: null, siteCount: 0, successionGap: false,
    active: false, disabledReason: "离职 —— 转甲方 CRA" }
];

/** 备案名册（`/v1/site-staff`）。**不是 STAFF_LIST 的一个投影** ——
 *  它的中心列表按行范围重算，而 STAFF_LIST 的 siteCount 数的是全部派工。
 *  两者在 mock 里就该是两份数据，否则"机构办数不出他在别家带几个"
 *  这条边界在 mock 上不成立，只有真库那一侧会暴露。
 *
 *  证书刻意排成三种：已过期（段志远 −12 天）、快到期（唐延 45 天）、
 *  还早（吴桐 410 天）、无记录（沈亦琳）。四种都摆，那一页的四个角标
 *  才都有东西可挂。 */
export interface MockSiteStaff {
  accountId: string; displayName: string; roleKind: string;
  gcpExpiresOn: string | null; gcpDaysLeft: number | null; active: boolean;
  sites: { id: string; code: string; hospital: string;
           studyShortName: string; since: string }[];
}
const at = (i: number, since: string) => ({
  id: SITES[i]!.id, code: SITES[i]!.code, hospital: SITES[i]!.hospital,
  studyShortName: "艾瑞替尼 III", since
});
export const SITE_STAFF: MockSiteStaff[] = [
  { accountId: "a-wutong", displayName: "吴桐", roleKind: "CRC", ...gcp(410),
    active: true, sites: [at(0, "2024-09-01"), at(1, "2025-03-04")] },
  { accountId: "a-tangyan", displayName: "唐延", roleKind: "CRC", ...gcp(45),
    active: true, sites: [at(0, "2025-06-16")] },
  /* 证书过期的这一位在协和 —— 机构办一进页面就该看见他。 */
  { accountId: "a-duan", displayName: "段志远", roleKind: "CRA", ...gcp(-12),
    active: true, sites: [at(0, "2024-09-01"), at(2, "2025-01-13")] },
  { accountId: "a-shen", displayName: "沈亦琳", roleKind: "CRC", ...gcp(null),
    active: true, sites: [at(1, "2025-08-11")] },
  /* 已停用但**留在名册上**：他上周还在中心里出现过。 */
  { accountId: "a-zhouqi", displayName: "周琦", roleKind: "CRA", ...gcp(120),
    active: false, sites: [at(0, "2024-11-05")] }
];

/** 候选中心（可行性调查）。
 *
 *  **五条各有各的用处**，缺一条界面上就有一条分支画不出来：
 *   · 一条高分待定 —— 「入选不用写理由」那条路要走得通
 *   · 一条低分待定 —— 「低分入选必须写理由」是这一页最要紧的一条规则
 *   · 一条低分已入选、实际入组 0    —— 「当初说了不行」的兑现
 *   · 一条入排匹配度为 null        —— 「当时没问过」和「填了 0」要分得开
 *   · 一条预测撞到病源上限          —— 「瓶颈是病人不是团队」
 *
 *  分数不在这里写死：mock 只出问卷答案，评分由**契约里那套口径**
 *  在服务端算。mock 自己算一遍等于第三套口径。 */
export interface MockFeas {
  id: string; code: string;
  study: { id: string; code: string; shortName: string };
  hospital: string; city: string; dept: string; piName: string;
  surveyedOn: string; surveyedByName: string | null;
  answers: {
    ptYear: number; pastN: number; pastBest: number; compet: number;
    ethicsDays: number; startDays: number; teamN: number; piCommit: number;
    eligPct: number | null;
  };
  status: "assessing" | "selected" | "rejected";
  decidedOn: string | null; decidedByName: string | null;
  studySiteId: string | null; siteCode: string | null;
  overrideReason: string | null; rejectReason: string | null;
  actualRate: number | null;
}
const STUDY = { id: "st1", code: "HJ-2024-017", shortName: "艾瑞替尼 III" };
export function mkFeas(): MockFeas[] {
  return [
    /* 高分待定：入选不用写理由 */
    { id: "fs1", code: "FS-2026-014", study: STUDY,
      hospital: "浙江大学医学院附属第二医院", city: "杭州", dept: "心内科",
      piName: "施允中", surveyedOn: "2026-08-12", surveyedByName: "何雨薇",
      answers: { ptYear: 520, pastN: 6, pastBest: 5.5, compet: 1, ethicsDays: 38,
                 startDays: 52, teamN: 8, piCommit: 6.0, eligPct: 0.34 },
      status: "assessing", decidedOn: null, decidedByName: null,
      studySiteId: null, siteCode: null,
      overrideReason: null, rejectReason: null, actualRate: null },
    /* 低分待定：入选必须写理由。竞争试验 4 个、既往只做过 1 次 */
    { id: "fs2", code: "FS-2026-015", study: STUDY,
      hospital: "福建省立医院", city: "福州", dept: "心内科",
      piName: "林彦成", surveyedOn: "2026-08-15", surveyedByName: "何雨薇",
      answers: { ptYear: 150, pastN: 1, pastBest: 0.8, compet: 4, ethicsDays: 66,
                 startDays: 98, teamN: 3, piCommit: 3.5, eligPct: 0.19 },
      status: "assessing", decidedOn: null, decidedByName: null,
      studySiteId: null, siteCode: null,
      overrideReason: null, rejectReason: null, actualRate: null },
    /* 低分入选、实际 0 例 —— 校准表里那个「当初说了不行」 */
    { id: "fs3", code: "FS-2025-002", study: STUDY,
      hospital: "西安交大第一附属医院", city: "西安", dept: "肝胆外科",
      piName: "白玉山", surveyedOn: "2025-04-16", surveyedByName: "段志远",
      answers: { ptYear: 45, pastN: 0, pastBest: 0, compet: 2, ethicsDays: 74,
                 startDays: 147, teamN: 3, piCommit: 2.0, eligPct: null },
      status: "selected", decidedOn: "2025-04-30", decidedByName: "凌远",
      studySiteId: null, siteCode: "SS-05",
      overrideReason: "为赶 FPI 时间点凑够中心数，明知评分偏低仍启动",
      rejectReason: null, actualRate: 0 },
    /* 入排匹配度为 null：那一栏当时问卷里没有 */
    { id: "fs4", code: "FS-2024-003", study: STUDY,
      hospital: "北京协和医院", city: "北京", dept: "肝胆外科",
      piName: "陈国栋", surveyedOn: "2024-09-20", surveyedByName: "林敏",
      answers: { ptYear: 280, pastN: 8, pastBest: 2.6, compet: 1, ethicsDays: 35,
                 startDays: 49, teamN: 7, piCommit: 3.0, eligPct: null },
      status: "selected", decidedOn: "2024-10-04", decidedByName: "凌远",
      studySiteId: "s1", siteCode: "SS-01",
      overrideReason: null, rejectReason: null, actualRate: 1.4 },
    /* 预测撞到病源上限：PI 报 5 例/月，但一年只看 60 例 */
    { id: "fs5", code: "FS-2024-006", study: STUDY,
      hospital: "四川大学华西医院", city: "成都", dept: "腹部肿瘤科",
      piName: "罗建平", surveyedOn: "2024-11-08", surveyedByName: "段志远",
      answers: { ptYear: 60, pastN: 2, pastBest: 1.4, compet: 3, ethicsDays: 58,
                 startDays: 112, teamN: 4, piCommit: 5.0, eligPct: null },
      status: "selected", decidedOn: "2024-11-22", decidedByName: "凌远",
      studySiteId: null, siteCode: "SS-04",
      overrideReason: "申办方指定：PI 为该适应症区域学术带头人，坚持纳入",
      rejectReason: null, actualRate: 0.5 }
  ];
}

/** 投标。**四条各有各的用处**：
 *   · 一条待定        —— 「回写结果」那条路要走得通
 *   · 一条中标        —— 成交价就是我们的价，偏差 0（用来稀释总体偏差）
 *   · 一条失标且知价  —— 失标偏差的样本
 *   · 一条失标问不到  —— 「不知道 ≠ 零」在界面上要看得见
 *  少最后一条，那条规矩在 mock 上就永远不出现。 */
export interface MockBid {
  id: string; code: string; sponsor: string; name: string;
  submittedOn: string; sites: number; subjects: number;
  ourQuoteCents: number; ourPersonDays: number;
  status: "pending" | "won" | "lost";
  decidedOn: string | null; winningPriceCents: number | null;
  ownerName: string | null; note: string | null;
}
export function mkBids(): MockBid[] {
  return [
    { id: "b1", code: "B-2026-11", sponsor: "中康制药",
      name: "恒糖宁 IV 期上市后研究", submittedOn: "2026-08-05",
      sites: 24, subjects: 600, ourQuoteCents: 2180_0000_00, ourPersonDays: 8420,
      status: "pending", decidedOn: null, winningPriceCents: null,
      ownerName: "韩雪", note: "老客户，对方已口头示意价格可接受" },
    { id: "b2", code: "B-2026-09", sponsor: "华拓生物",
      name: "艾瑞替尼 IIIb 期扩展", submittedOn: "2026-06-18",
      sites: 16, subjects: 320, ourQuoteCents: 1960_0000_00, ourPersonDays: 7150,
      status: "won", decidedOn: "2026-08-02", winningPriceCents: 1880_0000_00,
      ownerName: "韩雪", note: "降价 4.1% 成交，仍在毛利线上" },
    /* 差 21%：那次复盘的结论是「对方按 12 人天/例，我们按 19」 */
    { id: "b3", code: "B-2026-07", sponsor: "惠元制药", name: "HY-207 II 期",
      submittedOn: "2026-05-22", sites: 8, subjects: 120,
      ourQuoteCents: 1120_0000_00, ourPersonDays: 4100,
      status: "lost", decidedOn: "2026-07-06", winningPriceCents: 890_0000_00,
      ownerName: "岑迪", note: "输给报价低 21% 的同行 —— 对方按 12 人天/例，我们按 19" },
    /* 问不到对手价的那一标。**它不进偏差统计** */
    { id: "b4", code: "B-2025-08", sponsor: "华拓生物", name: "HT-90 生物等效性",
      submittedOn: "2025-07-11", sites: 2, subjects: 48,
      ourQuoteCents: 320_0000_00, ourPersonDays: 980,
      status: "lost", decidedOn: "2025-08-25", winningPriceCents: null,
      ownerName: "岑迪", note: "对方未披露报价。BE 试验我们没有成本优势，之后不再投" }
  ];
}

/** 合同变更。**四条覆盖四种状态**，而且要有一条「每例」的：
 *  一条「每例 0.8 人天 × 143 例」在界面上是 114 人天，
 *  而它在提出那天只有十几例 —— 那条「入组越多白做越多」的话
 *  非得有这样一条才说得出来。 */
export interface MockChange {
  id: string; code: string;
  study: { id: string; code: string; shortName: string };
  studySiteId: string | null; siteCode: string | null;
  kind: string; kindLabel: string;
  raisedOn: string; raisedByName: string | null; what: string;
  personDaysImpact: number; perSubject: boolean; affectedSubjects: number;
  amountCents: number | null;
  status: "draft" | "submitted" | "signed" | "rejected";
  decidedOn: string | null; note: string | null;
}
export function mkChanges(): MockChange[] {
  const st = { id: "st1", code: "HJ-2024-017", shortName: "艾瑞替尼 III" };
  return [
    { id: "c1", code: "CR-2026-014", study: st,
      studySiteId: SITES[1]!.id, siteCode: SITES[1]!.code,
      kind: "exam_add", kindLabel: "方案修订 · 检查项增加",
      raisedOn: "2026-08-18", raisedByName: "吴桐",
      what: "方案 V3.0 → V3.1，C4 起每例增加心肌酶检测 2 次采血，CRC 每例多约 1.5 人天",
      personDaysImpact: 1.5, perSubject: true, affectedSubjects: 42,
      amountCents: null, status: "draft", decidedOn: null,
      note: "伦理已受理（E-0089），但商务侧尚未提出变更" },
    { id: "c2", code: "CR-2026-013", study: st,
      studySiteId: null, siteCode: null,
      kind: "extend", kindLabel: "周期延长",
      raisedOn: "2026-07-30", raisedByName: "韩雪",
      what: "入组滞后，整体周期由 27 个月延长至 31 个月，4 个月的 PM 与 CRA 驻场成本未覆盖",
      personDaysImpact: 260, perSubject: false, affectedSubjects: 0,
      amountCents: null, status: "submitted", decidedOn: null,
      note: "申办方以「延长系我方入组不力」为由暂未签署" },
    { id: "c3", code: "CR-2026-012", study: st,
      studySiteId: SITES[0]!.id, siteCode: SITES[0]!.code,
      kind: "subject_adj", kindLabel: "例数调整",
      raisedOn: "2026-06-12", raisedByName: "岑迪",
      what: "该中心筛败率 57%，合同 30 例下调至 20 例，同时上调单例单价补偿筛败成本",
      personDaysImpact: -180, perSubject: false, affectedSubjects: 0,
      amountCents: -18_5000_00, status: "signed", decidedOn: "2026-07-12",
      note: "已生效，单价由 3.9 调至 4.4 万" },
    /* 未获批但**仍然算白做** —— 这一条是整页最要紧的那句话 */
    { id: "c4", code: "CR-2026-010", study: st,
      studySiteId: SITES[0]!.id, siteCode: SITES[0]!.code,
      kind: "visit_add", kindLabel: "方案修订 · 访视增加",
      raisedOn: "2026-03-14", raisedByName: "吴桐",
      what: "新增 EOT 后 30 天安全随访访视 1 次",
      personDaysImpact: 0.8, perSubject: true, affectedSubjects: 143,
      amountCents: null, status: "rejected", decidedOn: "2026-04-13",
      note: "申办方认为属安全性义务，不追加费用" }
  ];
}

/** 客户。**账期各不相同是有意的** —— 现金流那一页的到期日全从它算，
 *  四家都是 60 天的话，「月结 45 天和 90 天差一个半月」那句话演不出来。 */
export interface MockClient {
  id: string; name: string; sinceYear: number | null; contact: string | null;
  paymentTermsDays: number; nps: number | null; note: string | null;
  studyCount: number; siteCount: number; enrolled: number; plannedSubjects: number;
  contractCents: number;
}
export const CLIENTS: MockClient[] = [
  { id: "cl1", name: "华拓生物", sinceYear: 2021, contact: "临床运营部 · 邵敏",
    paymentTermsDays: 60, nps: 8, note: "合作最久，付款守约，但压价最狠",
    studyCount: 1, siteCount: 2, enrolled: 24, plannedSubjects: 240,
    contractCents: 1860_0000_00 },
  /* 账期 90 天的那一家 —— 「下次报价要把资金成本算进去」那条提示要有对象。 */
  { id: "cl2", name: "安泰医药", sinceYear: 2024, contact: "医学部 · 骆一鸣",
    paymentTermsDays: 90, nps: 6, note: "账期长，两笔逾期均出自这里",
    studyCount: 1, siteCount: 1, enrolled: 8, plannedSubjects: 96,
    contractCents: 920_0000_00 }
];

/** 里程碑。**四条覆盖三种状态 + 两档逾期**：
 *   · 待开票      —— 「达成了没开票」那一格（记录缺口）
 *   · 已开票未逾期
 *   · 逾期 38 天  —— 一般逾期
 *   · 逾期 94 天  —— 超过 60 天，「不再是催收问题」
 *  再加一条已回款的，好让"已回款沉到最后"看得出来。 */
export interface MockMilestone {
  id: string; code: string; studySiteId: string; siteCode: string; hospital: string;
  study: { id: string; code: string; shortName: string };
  clientName: string; planCode: string; planLabel: string;
  milestoneCents: number; reachedOn: string;
  state: "pending" | "invoiced" | "paid";
  invoicedOn: string | null; dueOn: string | null; paidOn: string | null;
  note: string | null;
}
export function mkMilestones(): MockMilestone[] {
  const st = { id: "st1", code: "HJ-2024-017", shortName: "艾瑞替尼 III" };
  const at = (i: number) => ({
    studySiteId: SITES[i]!.id, siteCode: SITES[i]!.code, hospital: SITES[i]!.hospital
  });
  const d = (n: number) => shift(TODAY, n);
  return [
    { id: "ms1", code: "M-046", ...at(2), study: st, clientName: "华拓生物",
      planCode: "contract", planLabel: "合同签署", milestoneCents: 8_5000_00,
      reachedOn: d(-2), state: "pending",
      invoicedOn: null, dueOn: null, paidOn: null,
      note: "中心刚签，还没走开票流程" },
    { id: "ms2", code: "M-041", ...at(0), study: st, clientName: "华拓生物",
      planCode: "eighty", planLabel: "入组达成 80%", milestoneCents: 42_0000_00,
      reachedOn: d(-10), state: "invoiced",
      invoicedOn: d(-10), dueOn: d(50), paidOn: null, note: null },
    { id: "ms3", code: "M-035", ...at(1), study: st, clientName: "安泰医药",
      planCode: "eighty", planLabel: "入组达成 80%", milestoneCents: 38_6000_00,
      reachedOn: d(-128), state: "invoiced",
      invoicedOn: d(-128), dueOn: d(-38), paidOn: null, note: null },
    /* 逾期 94 天 —— 超过 60 天那条线 */
    { id: "ms4", code: "M-026", ...at(1), study: st, clientName: "安泰医药",
      planCode: "half", planLabel: "入组过半", milestoneCents: 33_6000_00,
      reachedOn: d(-184), state: "invoiced",
      invoicedOn: d(-184), dueOn: d(-94), paidOn: null,
      note: "催过两次，对方称在走内部流程" },
    { id: "ms5", code: "M-018", ...at(0), study: st, clientName: "华拓生物",
      planCode: "half", planLabel: "入组过半", milestoneCents: 40_6000_00,
      reachedOn: d(-212), state: "paid",
      invoicedOn: d(-212), dueOn: d(-152), paidOn: d(-150), note: null }
  ];
}

/** 工作类型 → 中文名与是否可计费。与库里的 work_type 表同一套口径：
 *  billable 由类型推导，提交时**落库固化**（I1）—— 所以 mock 也必须
 *  在创建那一刻把它定下来，而不是渲染时再查表。 */
export const WORK_TYPE_META: Record<string, { label: string; billable: boolean }> = {
  visit_support: { label: "受试者访视陪同", billable: true },
  sdv:           { label: "源数据准备与核对", billable: true },
  ethics:        { label: "伦理递交与跟进", billable: true },
  monitoring:    { label: "现场监查（IMV）", billable: true },
  ip_mgmt:       { label: "药品与物资管理", billable: true },
  training:      { label: "内部培训", billable: false },
  bd:            { label: "投标与商务支持", billable: false },
  rework:        { label: "返工与整改", billable: false }
};

/** 现行费率卡：CRC 通用 1180 元/人天。第二张已收口，用来演示"调价是两步"。 */
function makeRateCards(): MockRateCard[] {
  return [
    { id: "rc-crc-2026", roleKind: "CRC", level: null, dayCostCents: 118000,
      validFrom: "2026-01-01", validTo: null, note: "2026 年度" },
    { id: "rc-crc-2025", roleKind: "CRC", level: null, dayCostCents: 106000,
      validFrom: "2025-01-01", validTo: "2025-12-31", note: "2025 年度（已收口）" },
    { id: "rc-cra-2026", roleKind: "CRA", level: null, dayCostCents: 129800,
      validFrom: "2026-01-01", validTo: null, note: "2026 年度" }
  ];
}

const DAY_COST = 118000;
/** 与 calc 的 entryCostCents 同一个式子 —— mock 里也不另立口径。 */
const cost = (hours: number, travel = 0) =>
  Math.round((hours / 8) * DAY_COST) + travel;

export function mkTimesheet(
  id: string, site: typeof SITES[number], workDate: string, workType: string,
  hours: number, opts: { travel?: number; auto?: boolean; note?: string } = {}
): MockTimesheet {
  const meta = WORK_TYPE_META[workType]!;
  const travel = opts.travel ?? 0;
  return {
    id, studySiteId: site.id, siteCode: site.code,
    accountId: "a-wutong", personName: "吴桐",
    workDate, workType, workTypeLabel: meta.label, billable: meta.billable,
    hours, dayCostCents: DAY_COST, travelCents: travel,
    costCents: cost(hours, travel), rateCardId: "rc-crc-2026",
    subjectId: null, visitId: null,
    autoGenerated: opts.auto ?? false, note: opts.note ?? null,
    voidedAt: null, voidedByName: null, voidReason: null,
    createdAt: new Date().toISOString(),
    /* 演示数据里**故意一半没审**：全都审过的话，"待审"角标、
       "只看待审"筛选、损益上的"其中多少还没审"三处都画不出来，
       也就没人会发现它们其实没写对。 */
    approvedAt: null, approvedByName: null
  };
}

function makeTimesheets(): MockTimesheet[] {
  return [
    mkTimesheet("ts-1", SITES[0]!, shift(TODAY, -1), "visit_support", 3.5,
      { travel: 8600, note: "S-0203 C8D1 陪同" }),
    /* 一条已审过的：三处审批相关的界面（角标、筛选、损益上的"其中多少
       还没审"）都要有两种状态才画得出来。 */
    { ...mkTimesheet("ts-2", SITES[0]!, shift(TODAY, -2), "sdv", 5),
      approvedAt: shift(TODAY, -1) + "T09:00:00+08:00", approvedByName: "韩雪" },
    /* 不可计费的那一条：占比高说明人力花在了卖不出去的事情上 */
    mkTimesheet("ts-3", SITES[1]!, shift(TODAY, -3), "training", 2),
    /* **一条属于经营层自己的。** 「待我审批」那一页要能演示
       "不能审自己填的"：全部工时都属于别人的话，那条规则在界面上
       永远不出现，而它恰恰是审批流唯一的价值所在。 */
    { ...mkTimesheet("ts-4", SITES[0]!, shift(TODAY, -5), "monitoring", 4),
      accountId: "a-lingyuan", personName: "凌远" }
  ];
}

export const SITE_BY_ID = Object.fromEntries(SITES.map(s => [s.id, s]));
export const SITES_LIST = SITES;


/* ── SAE 与药品：演示数据 ───────────────────────────────────────────
   都挂在 SITES[0]（s1）上。数字刻意不圆整 ——
   "24.0 小时"看起来像占位符，"31.5 小时"看起来像真的发生过。 */
const hoursAgo = (h: number) => new Date(TODAY.getTime() - h * 3_600_000).toISOString();

function makeSaes(): Scenario["qualityEvents"] {
  const site = SITES[0]!;
  const base = {
    siteCode: site.code, studySiteId: site.id, kind: "sae", severity: "critical",
    state: "open", autoGenerated: false, raisedBy: "cra", ageDays: 2,
    sourceEventId: null
  };
  return [
    { ...base, id: "sae1", code: "SAE-DEMO01",
      title: "受试者出现 III 度中性粒细胞减少",
      detail: "住院对症治疗，研究者判定与试验药物可能相关。",
      raisedOn: hoursAgo(31.5).slice(0, 10),
      occurredAt: hoursAgo(31.5), reportedAt: hoursAgo(23) },   // 8.5 小时，按时
    { ...base, id: "sae2", code: "SAE-DEMO02",
      title: "受试者因肝功能异常住院",
      detail: "尚在整理上报材料 —— 已经超过 24 小时。",
      raisedOn: hoursAgo(52).slice(0, 10),
      occurredAt: hoursAgo(52), reportedAt: null }              // 52 小时未报 = 迟报
  ];
}

/** SAE 之外的质量事件。**机构质控那一页要的是这几条** ——
 *  只摆两条 SAE 的话，那一页上"重的排前面""挂了 30 天以上"
 *  两条分支永远画不出来，也就没人会发现它们其实没写对。
 *
 *  三条各有用处：
 *   · 一条挂了 60 天的重大偏离 —— 逾期那个角标要有东西可挂
 *   · 一条自动生成的（访视超窗触发）—— "系统自动"那一栏要有对照
 *   · 一条在 SS-07 —— 机构办（协和）**不该看见它**，行范围才演得出来 */
function makeQualityEvents(): Scenario["qualityEvents"] {
  const base = {
    autoGenerated: false, sourceEventId: null,
    occurredAt: null, reportedAt: null
  };
  return [
    { ...base, id: "qa1", code: "QA-2026-0071",
      siteCode: SITES[0]!.code, studySiteId: SITES[0]!.id,
      kind: "deviation", severity: "major", state: "open",
      title: "两例受试者的知情同意版本落后一个版本",
      detail: "IRB 批件已更新至 v3.1，中心仍在用 v3.0 签署。",
      raisedBy: "institution", raisedOn: shift(TODAY, -60), ageDays: 60,
      /* **已指派、还没提交整改措施。** 它不是「正在整改」——
         是有人欠着一份措施，而这两件事在判定上必须分得开。 */
      category: "知情同意版本错误",
      capaPlan: null,
      capaOwnerAccountId: "a-wutong", capaOwnerName: "吴桐",
      capaDueOn: shift(TODAY, -2) },
    { ...base, id: "qa2", code: "QA-2026-0088",
      siteCode: SITES[0]!.code, studySiteId: SITES[0]!.id,
      kind: "deviation", severity: "minor", state: "open",
      title: "C4D1 访视超出窗口 3 天",
      detail: "完成日 2026-08-21，窗口关闭日 2026-08-18。",
      autoGenerated: true,
      raisedBy: "system", raisedOn: shift(TODAY, -6), ageDays: 6,
      category: "方案偏离",
      capaPlan: "CRC 增加访视窗口前 7 天提醒机制；PI 签署方案偏离表并上报伦理。",
      capaOwnerAccountId: "a-wutong", capaOwnerName: "吴桐",
      capaDueOn: shift(TODAY, 8) },
    { ...base, id: "qa3", code: "QA-2026-0090",
      siteCode: SITES[1]!.code, studySiteId: SITES[1]!.id,
      kind: "ip_discrepancy", severity: "major", state: "open",
      title: "药品回收数量与发放记录差 2 盒",
      detail: "中心称已发给受试者但未登记，正在核对。",
      raisedBy: "cra", raisedOn: shift(TODAY, -9), ageDays: 9,
      category: "药品不平衡",
      capaPlan: "逐笔核对发放登记与药房出库记录；发放当场双人签字确认。",
      capaOwnerAccountId: "a-liaomeng", capaOwnerName: "廖萌",
      capaDueOn: shift(TODAY, 12) },
    /* **这一条是复发的源头。** 它的 CAPA 写的是「集中补签并留痕」——
       那是纠正，不是预防：补完签名，下个月照样缺。
       稽查 AU-2026-005 正是在它还开着的时候又发现了同一个问题。 */
    { ...base, id: "qa4", code: "QI-2026-0151",
      siteCode: SITES[0]!.code, studySiteId: SITES[0]!.id,
      kind: "other", severity: "minor", state: "open",
      title: "源数据缺陷",
      detail: "稽查抽查 20 份原始病历，12 处研究者签名/日期缺失，集中在合并用药记录页。",
      raisedBy: "sponsor", raisedOn: shift(TODAY, -46), ageDays: 46,
      category: "源数据缺陷",
      capaPlan: "研究者集中补签并留痕。",
      capaOwnerAccountId: "a-wutong", capaOwnerName: "吴桐",
      capaDueOn: shift(TODAY, -3) },
    /* 已关闭且没复发 —— 「有效」那一档要有对照。 */
    { ...base, id: "qa5", code: "QI-2026-0131",
      siteCode: SITES[0]!.code, studySiteId: SITES[0]!.id,
      kind: "other", severity: "minor", state: "closed",
      title: "实验室资质过期",
      detail: "中心检验科室间质评证书到期，新证书未及时归档至研究者文件夹。",
      raisedBy: "institution", raisedOn: shift(TODAY, -66), ageDays: 66,
      category: "实验室资质过期",
      capaPlan: "已取得新证书并归档；建立中心资质文件到期日历，提前 60 天提醒。",
      capaOwnerAccountId: "a-wutong", capaOwnerName: "吴桐",
      capaDueOn: shift(TODAY, -20) }
  ];
}

export interface MockQuery {
  id: string; code: string;
  studySiteId: string; siteCode: string; hospital: string; studyShortName: string;
  subjectId: string | null; screeningNo?: string;
  form: string; fieldName: string; detail: string;
  severity: string; state: string;
  raisedBy: string; raisedByName: string | null; raisedOn: string;
  ownerAccountId: string | null; ownerName: string | null;
  answer: string | null; answeredOn: string | null; returnedReason: string | null;
  chaseCount: number; lastChasedOn: string | null;
  closedAt: string | null; resolution: string | null;
  ageDays: number; stale: boolean;
}

/** 数据质疑。**每一条都在替一个分支站岗** ——
 *  编一批"都挂了 3 天、都在同一个中心"的数据，两页画得出来，
 *  但页面上一半的判断永远走不到，也就没人会发现它们其实没写对：
 *
 *   · 挂了 21 天的  —— 超 7 天那个角标、以及催办按钮；
 *   · 一条已回复的  —— DM 的「待我关闭」那一栏，和 CRC 的「已回复」栏；
 *   · 一条已关闭的  —— 平均挂起里"未关闭的也算进去"要有对照；
 *   · SS-01 上三条同一个表单 —— 归因结论走「表单难填」；
 *   · SS-07 上三条各不相同 —— 走「录入质量」。
 *  两个结论各有数据支撑，那句"高不一定是中心差"才不是免责声明。 */
function makeDataQueries(): MockQuery[] {
  const s1 = SITES[0]!, s2 = SITES[1]!;
  const mk = (
    id: string, code: string, site: typeof SITES[number], subjectId: string | null,
    screeningNo: string | null, form: string, fieldName: string, detail: string,
    ageDays: number, state: string, owner: [string, string],
    extra: Partial<MockQuery> = {}
  ): MockQuery => ({
    id, code, studySiteId: site.id, siteCode: site.code, hospital: site.hospital,
    studyShortName: "艾瑞替尼 III",
    subjectId, ...(screeningNo ? { screeningNo } : {}),
    form, fieldName, detail,
    severity: ageDays > 7 ? "major" : "minor", state,
    raisedBy: "dm", raisedByName: "苗青", raisedOn: shift(TODAY, -ageDays),
    ownerAccountId: owner[0], ownerName: owner[1],
    answer: null, answeredOn: null, returnedReason: null,
    chaseCount: 0, lastChasedOn: null,
    closedAt: null, resolution: null,
    ageDays, stale: state === "open" && ageDays > 7,
    ...extra
  });
  const WU: [string, string] = ["a-wutong", "吴桐"];
  const LIAO: [string, string] = ["a-liaomeng", "廖萌"];

  return [
    /* SS-01：三条都在合并用药 CM 上 —— 这个表单本身难填，不是这家中心差。 */
    mk("q1", "Q-1176", s1, "u1", "S-0203", "合并用药 CM", "起始日期",
      "CM 起始日期（2026-07-30）早于知情同意签署日期（2026-08-02），请核实源数据。",
      21, "open", WU),
    /* **这一条被退回过。** 退回是个真实存在的状态，不是只能靠点一遍才看得见 ——
       固定摆一条，CRC 那一页「上次为什么被退回」的那一格才有东西可画。 */
    mk("q2", "Q-1182", s1, "u1", "S-0203", "合并用药 CM", "剂量单位",
      "同一种药前后两次记录的剂量单位不一致（mg 与 mg/kg），请统一并核实。",
      9, "open", WU, {
        answer: "已按医嘱单核对，两处都是 mg。",
        answeredOn: shift(TODAY, -4),
        returnedReason: "回复未提供源数据依据，请附医嘱单页码或扫描件。"
      }),
    mk("q3", "Q-1190", s1, "u-102", "SS-01-P0102", "合并用药 CM", "结束日期",
      "CM 结束日期为空但用药状态标为「已停用」，请补齐或更正状态。",
      3, "open", WU),
    /* 一条已回复待关闭 —— DM 的「待我关闭」和「回复合格才能关」都靠它。 */
    mk("q4", "Q-1165", s1, "u1", "S-0203", "生命体征 VS", "收缩压",
      "收缩压 210 mmHg 超出合理区间，疑为录入错误。",
      12, "pending_review", WU, {
        answer: "已调阅原始护理记录：该次收缩压为 120 mmHg，eCRF 录入时多输一位，" +
          "已更正为 120，源文件见门诊病历第 7 页。",
        answeredOn: shift(TODAY, -2)
      }),
    /* SS-07：三条散在三个表单 —— 这才是录入质量问题。 */
    mk("q5", "Q-1155", s2, "u2", "S-0331", "访视日期 SV", "实际访视日期",
      "第 4 次访视超出方案窗口 5 天，请提供方案偏离说明及 PI 签字。",
      16, "open", LIAO),
    mk("q6", "Q-1171", s2, "u2", "S-0331", "疗效评估 RS", "靶病灶长径",
      "基线与 C4 靶病灶数量不一致（3 → 2），请补充说明。",
      6, "open", LIAO),
    mk("q7", "Q-1188", s2, "u2", "S-0331", "用药依从性 EX", "回收片数",
      "发放 90 片、回收 12 片、服用记录 71 片，三者不平，请核对。",
      4, "open", LIAO),
    /* 一条已关闭 —— 「平均挂起把未关闭的也算进去」要有对照才说得清。 */
    mk("q8", "Q-1140", s2, "u2", "S-0331", "实验室检查 LB", "中性粒细胞计数",
      "C2D1 中性粒细胞 0.9×10⁹/L 已达 3 级，但未见对应 AE 记录，请确认是否漏报。",
      2, "closed", LIAO, {
        answer: "已确认为漏报，已补录 AE「3 级中性粒细胞减少」，起止日期与检验报告一致。",
        answeredOn: shift(TODAY, -1),
        closedAt: new Date(Date.now() - 86_400_000).toISOString(),
        resolution: "回复合格，已核对源数据与补录的 AE"
      })
  ];
}

export interface MockMonitorItem {
  seq: number; task: string; doneAt: string | null; doneByName: string | null;
}
export interface MockMonitorVisit {
  id: string; code: string;
  studySiteId: string; siteCode: string; hospital: string; studyShortName: string;
  kind: string; plannedOn: string;
  monitorAccountId: string; monitorName: string;
  days: number; state: string;
  confirmedOn: string | null; performedOn: string | null; reportSubmittedOn: string | null;
  sdvSamplePct: number | null; note: string | null;
  items: MockMonitorItem[];
}

/** 监查访视。**每一条都在替一个分支站岗**：
 *   · 两条已交报告的  —— 「上一次去是什么时候」要有答案；
 *   · 一条去了没交的  —— MVR 欠账，原型里连一个状态都没有；
 *   · 一条过了计划日还没去 —— 和上一条是**两个**不同的欠账；
 *   · 一条待确认的    —— 中心那边还不知道我们要去；
 *   · SS-14 一条都没有 —— 「一次都没监查过」不是「刚去过」。
 *  编一批"都已排期、都在同一个中心"的数据，页面画得出来，
 *  但一半的判断永远走不到。 */
function makeMonitorVisits(): MockMonitorVisit[] {
  const s1 = SITES[0]!, s2 = SITES[1]!;
  const CRA: [string, string] = ["a-linmin", "林敏"];
  /* plannedOn 已经是字符串了，而 shift() 收的是 Date —— 这里单独一个。 */
  const back = (d: string, n: number) =>
    new Date(Date.parse(d) - n * 86_400_000).toISOString().slice(0, 10);
  const routine = [
    "SDV：本期新增受试者源数据核对",
    "试验用药品发放与回收记录清点",
    "未关闭质量事件与数据质疑跟进"
  ];
  const mk = (
    id: string, code: string, site: typeof SITES[number], kind: string,
    plannedOn: string, state: string, days: number,
    extra: Partial<MockMonitorVisit> = {},
    tasks: { t: string; done: boolean }[] = routine.map(t => ({ t, done: true }))
  ): MockMonitorVisit => ({
    id, code,
    studySiteId: site.id, siteCode: site.code, hospital: site.hospital,
    studyShortName: "艾瑞替尼 III",
    kind, plannedOn,
    monitorAccountId: CRA[0], monitorName: CRA[1],
    days, state,
    confirmedOn: state === "proposed" ? null : back(plannedOn, 10),
    performedOn: state === "done" || state === "reported" ? plannedOn : null,
    reportSubmittedOn: null,
    sdvSamplePct: null, note: null,
    items: tasks.map((x, seq) => ({
      seq, task: x.t,
      doneAt: x.done ? `${plannedOn}T09:00:00.000Z` : null,
      doneByName: x.done ? CRA[1] : null
    })),
    ...extra
  });

  return [
    mk("mv1", "MV-2026-001", s1, "imv", shift(TODAY, -120), "reported", 1,
      { reportSubmittedOn: shift(TODAY, -115), sdvSamplePct: 50 }),
    mk("mv2", "MV-2026-002", s1, "imv", shift(TODAY, -50), "reported", 1,
      { reportSubmittedOn: shift(TODAY, -44), sdvSamplePct: 50 }),
    /* 去过了，报告压着 —— 最常见的欠账 */
    mk("mv3", "MV-2026-003", s1, "imv", shift(TODAY, -21), "done", 2, {},
      [{ t: "跟进 QI-2026-0155 SAE 上报 CAPA 执行证据", done: true },
       { t: "核对试验用药品发放与回收记录，清点库存", done: false },
       { t: "研究者文件夹（ISF）完整性检查表逐项过", done: false }]),
    /* SS-07 上一次去还是五个多月前 —— **逾期未监查**那一格要有东西可挂。
       它和"排了期没去"是两回事：那一条说的是这一次，这一条说的是这个中心。 */
    mk("mv6", "MV-2026-006", s2, "imv", shift(TODAY, -160), "reported", 1,
      { reportSubmittedOn: shift(TODAY, -152), sdvSamplePct: 100 }),
    /* 排了期、也确认了，但计划日过了人还没去 —— 和上一条不是同一个问题 */
    mk("mv4", "MV-2026-004", s2, "imv", shift(TODAY, -6), "scheduled", 2, {},
      [{ t: "入组停滞根因访谈：PI 与研究护士各 30 分钟", done: false },
       { t: "复核筛选失败日志，统计失败原因分布", done: false }]),
    /* 待确认：中心那边还不知道我们要去 */
    mk("mv5", "MV-2026-005", s2, "cov", shift(TODAY, 12), "proposed", 2, {},
      [{ t: "全部受试者随访完成确认，末例出组日期锁定", done: false },
       { t: "剩余药品回收销毁记录", done: false },
       { t: "研究者文件夹归档移交清单", done: false }])
  ];
}

export interface MockAuditFinding {
  seq: number; severity: string; finding: string;
  repeatOf: string | null; repeatOfCode: string | null;
  repeatAfterClose: boolean | null;
  state: string; verification: string | null; closedAt: string | null;
}
export interface MockAudit {
  id: string; code: string;
  studySiteId: string; siteCode: string; hospital: string;
  kind: string; auditedOn: string;
  auditorAccountId: string; auditorName: string;
  scope: string; state: string; closedAt: string | null;
  findings: MockAuditFinding[];
}

/** 内部稽查。**三条各站一个分支**：
 *   · 一条带复发发现 —— CAPA 有效性那张表唯一要人动手的那一行；
 *   · 一条已结案     —— 「有效」的对照；
 *   · 一条刚发起、还没有发现项 —— 「进行中」和「待整改」是两个状态。 */
function makeAudits(): MockAudit[] {
  const s1 = SITES[0]!, s2 = SITES[1]!;
  const QA: [string, string] = ["a-weilan", "卫兰"];
  const mk = (
    id: string, code: string, site: typeof SITES[number], kind: string,
    daysAgo: number, state: string, scope: string, findings: MockAuditFinding[]
  ): MockAudit => ({
    id, code,
    studySiteId: site.id, siteCode: site.code, hospital: site.hospital,
    kind, auditedOn: shift(TODAY, -daysAgo),
    auditorAccountId: QA[0], auditorName: QA[1],
    scope, state,
    closedAt: state === "closed" ? `${shift(TODAY, -daysAgo)}T09:00:00.000Z` : null,
    findings
  });
  const f = (
    seq: number, severity: string, finding: string,
    extra: Partial<MockAuditFinding> = {}
  ): MockAuditFinding => ({
    seq, severity, finding,
    repeatOf: null, repeatOfCode: null, repeatAfterClose: null,
    state: "open", verification: null, closedAt: null, ...extra
  });

  return [
    mk("au1", "AU-2026-005", s1, "site", 27, "remediating",
      "针对筛败率异常与源数据签名缺失的专项稽查", [
        f(0, "major", "筛选失败日志未按 SOP 逐例记录失败原因，26 例中 11 例原因栏为空"),
        /* **复发**：源事件还在整改中就又出现了 —— 比"关闭后复发"更急，
           它说明现在正在做的措施没有用。 */
        f(1, "major", "研究者签名缺日期共 12 处，此前 QI-2026-0151 已提出，本次复发", {
          repeatOf: "qa4", repeatOfCode: "QI-2026-0151", repeatAfterClose: false
        })
      ]),
    mk("au2", "AU-2026-003", s2, "site", 76, "closed",
      "入组停滞根因专项", [
        f(0, "minor", "预筛记录不完整，无法还原病源实际规模", {
          state: "closed",
          verification: "已抽查复核，预筛登记表补齐并留痕，问题未再出现",
          closedAt: `${shift(TODAY, -70)}T09:00:00.000Z`
        })
      ]),
    mk("au3", "AU-2026-006", s1, "capa_check", 13, "open",
      "验证 QI-2026-0131（实验室资质过期）关闭后是否建立到期日历", [])
  ];
}

function makeIpMovements(): Scenario["ipMovements"] {
  const site = SITES[0]!;
  const on = (d: number) => shift(TODAY, d);
  const m = (id: string, kind: string, quantity: number,
             extra: Partial<Scenario["ipMovements"][number]> = {}) => ({
    id, studySiteId: site.id, movedOn: on(-30), kind, quantity,
    subjectRef: null, refNo: null, note: null, ...extra
  });
  /* 30 收 − 12 发 = 18 在手：关闭闸门会拦下它，而台账上说得出为什么。 */
  return [
    m("ip1", "receipt", 30, { refNo: "SF-2026-0011" }),
    m("ip2", "dispense", 12, { movedOn: on(-14), subjectRef: "S-0331" })
  ];
}

/* ── 入组漏斗 ──────────────────────────────────────────────────────
   三个中心刻意造成三种形状 —— 「入组慢」有三种完全不同的根因，
   而这两页存在的理由就是把它们分开：
     SS-01 预筛多、筛败高 → 要谈方案修订
     SS-07 预筛少、转化好 → 要加招募渠道
     SS-14 一例都没有     → 不是入组慢，是还没真正启动
   三个中心给一样的数的话，页面画得出来，但它想说的话一句也说不出来。 */
const ratio = (a: number, b: number) => b > 0 ? a / b : null;

const mkFunnel = (
  id: string, code: string, hospital: string, contracted: number,
  n: { prescreened: number; icfSigned: number; inScreening: number;
       enrolled: number; screenFailed: number; withdrawn: number; completed: number },
  screenFailBreakdown: { reason: string; count: number }[],
  withdrawBreakdown: { reason: string; count: number }[]
) => ({
  studySiteId: id, siteCode: code, hospital, contracted, ...n,
  screenFailRate: ratio(n.screenFailed, n.icfSigned),
  icfRate: ratio(n.icfSigned, n.prescreened),
  yieldRate: ratio(n.enrolled, n.prescreened),
  retentionRate: ratio(n.enrolled - n.withdrawn, n.enrolled),
  screenFailBreakdown, withdrawBreakdown,
  attainment: ratio(n.enrolled, contracted)
});

export const FUNNELS = [
  mkFunnel("s1", "SS-01", "北京协和医院", 20,
    { prescreened: 62, icfSigned: 41, inScreening: 4, enrolled: 24, screenFailed: 13,
      withdrawn: 3, completed: 6 },
    [{ reason: "imaging", count: 6 }, { reason: "lab", count: 4 },
     { reason: "comorbidity", count: 2 }, { reason: "withdrew_icf", count: 1 }],
    [{ reason: "adverse_event", count: 2 }, { reason: "lost_to_followup", count: 1 }]),
  mkFunnel("s2", "SS-07", "中山大学肿瘤防治中心", 18,
    { prescreened: 21, icfSigned: 16, inScreening: 2, enrolled: 12, screenFailed: 2,
      withdrawn: 1, completed: 3 },
    [{ reason: "lab", count: 2 }],
    [{ reason: "withdrew_icf", count: 1 }]),
  mkFunnel("s3", "SS-14", "江苏省人民医院", 12,
    { prescreened: 0, icfSigned: 0, inScreening: 0, enrolled: 0, screenFailed: 0,
      withdrawn: 0, completed: 0 },
    [], [])
];

/* ── 审计轨迹 ──────────────────────────────────────────────────────
   要造得出两类：权限变更（isSensitive）与日常写入。
   全是敏感的话，"默认只看权限类变更"这个开关就看不出作用；
   而那个开关正是这一页最重要的一个设计判断。 */
const ago = (h: number) => new Date(Date.now() - h * 3600_000).toISOString();

export const AUDIT_ENTRIES = [
  { id: "au1", at: ago(2), actorLogin: "lingyuan", actorRoleCode: "boss",
    action: "调整角色权限", targetType: "role", targetId: "cra",
    before: { visibleFields: ["subject"] },
    after: { visibleFields: ["subject", "price"] },
    studySiteId: null, reason: "本季度中心谈判需要 CRA 看得到报价", isSensitive: true },
  { id: "au2", at: ago(26), actorLogin: "lingyuan", actorRoleCode: "boss",
    action: "停用账号", targetType: "account", targetId: "zhouqi",
    before: { status: "active" }, after: { status: "disabled" },
    studySiteId: null, reason: "离职 —— 中心已交接给段志远", isSensitive: true },
  { id: "au3", at: ago(30), actorLogin: "admin", actorRoleCode: "admin",
    action: "重设账号口令", targetType: "account", targetId: "tangyan",
    before: null, after: { passwordIsInitial: true },
    studySiteId: null, reason: "新人入职，通道尚未配置", isSensitive: true },
  { id: "au4", at: ago(5), actorLogin: "wutong", actorRoleCode: "crc",
    action: "完成访视", targetType: "subject_visit", targetId: "v1",
    before: { status: "planned" }, after: { status: "done_pending_pi" },
    studySiteId: "s1", reason: null, isSensitive: false },
  { id: "au5", at: ago(9), actorLogin: "wutong", actorRoleCode: "crc",
    action: "填报工时", targetType: "timesheet_entry", targetId: "t-1",
    before: null, after: { hours: 3.5 },
    studySiteId: "s1", reason: null, isSensitive: false }
];

/* ── 受试者、补偿、伦理递交 ────────────────────────────────────────
   这三份是**可变的**：登记预筛、签知情、筛败、登记发放、登记批复
   都要当场看得见。造的形状同样是"三种情况"，不是三份一样的数据：

     P-0101 预筛，还没签知情        → 下一步是签 ICF
     P-0102 筛选中，等入组或筛败     → 两个按钮都该出现
     S-0203 已入组，下一次访视超窗   → 受试者窗口那页要把它顶到最上面
     S-0331 已入组，窗口内
     P-0099 已筛败                  → 不该再有下一步
*/
export interface MockSubject {
  id: string; studySiteId: string; siteCode: string;
  screeningNo: string; randomized: boolean; randomizationNo: string | null;
  state: string;
  icfSignedOn: string | null; enrolledOn: string | null; exitedOn: string | null;
  screenFailReason: string | null; withdrawReason: string | null;
  crcName: string | null;
  visitsDone: number; visitsPlanned: number;
  nextVisit: {
    id: string; seq: number; visitCode: string; visitLabel: string;
    targetDate: string; windowFrom: string; windowTo: string;
    daysLeft: number; outOfWindow: boolean;
  } | null;
}

export interface MockPayment {
  id: string; studySiteId: string; siteCode: string;
  subjectId: string; screeningNo: string;
  visitId: string | null; visitLabel: string | null;
  amountCents: number; dueOn: string;
  paidOn: string | null; receiptRef: string | null; ageDays: number;
}

export interface MockSubmission {
  id: string; studySiteId: string; kind: string;
  submittedOn: string; decision: string; decidedOn: string | null;
  refNo: string | null; note: string | null;
}

const day = (offset: number) =>
  new Date(Date.now() + offset * 86_400_000).toISOString().slice(0, 10);

const mkNext = (id: string, label: string, daysLeft: number) => ({
  id, seq: 4, visitCode: "C4D1", visitLabel: label,
  targetDate: day(daysLeft - 3), windowFrom: day(daysLeft - 6), windowTo: day(daysLeft),
  daysLeft, outOfWindow: daysLeft < 0
});

export const mkSubjects = (): MockSubject[] => [
  { id: "u-101", studySiteId: "s1", siteCode: "SS-01", screeningNo: "SS-01-P0101",
    randomized: false, randomizationNo: null, state: "prescreen",
    icfSignedOn: null, enrolledOn: null, exitedOn: null,
    screenFailReason: null, withdrawReason: null, crcName: "吴桐",
    visitsDone: 0, visitsPlanned: 0, nextVisit: null },
  { id: "u-102", studySiteId: "s1", siteCode: "SS-01", screeningNo: "SS-01-P0102",
    randomized: false, randomizationNo: null, state: "screening",
    icfSignedOn: day(-9), enrolledOn: null, exitedOn: null,
    screenFailReason: null, withdrawReason: null, crcName: "吴桐",
    visitsDone: 1, visitsPlanned: 8, nextVisit: mkNext("v-102", "筛选期评估", 5) },
  { id: "u1", studySiteId: "s1", siteCode: "SS-01", screeningNo: "S-0203",
    randomized: true, randomizationNo: "R-0203", state: "enrolled",
    icfSignedOn: day(-120), enrolledOn: day(-110), exitedOn: null,
    screenFailReason: null, withdrawReason: null, crcName: "吴桐",
    visitsDone: 5, visitsPlanned: 8, nextVisit: mkNext("v1", "C4D1 第 4 周期给药", -6) },
  { id: "u2", studySiteId: "s2", siteCode: "SS-07", screeningNo: "S-0331",
    randomized: true, randomizationNo: "R-0331", state: "enrolled",
    icfSignedOn: day(-80), enrolledOn: day(-72), exitedOn: null,
    screenFailReason: null, withdrawReason: null, crcName: "廖萌",
    visitsDone: 3, visitsPlanned: 8, nextVisit: mkNext("v3", "C3D1 给药 + 肿瘤评估", 12) },
  { id: "u-099", studySiteId: "s1", siteCode: "SS-01", screeningNo: "SS-01-P0099",
    randomized: false, randomizationNo: null, state: "screen_failed",
    icfSignedOn: day(-40), enrolledOn: null, exitedOn: day(-33),
    screenFailReason: "imaging", withdrawReason: null, crcName: "吴桐",
    visitsDone: 1, visitsPlanned: 8, nextVisit: null }
];

export const mkPayments = (): MockPayment[] => [
  /* 欠了 48 天 —— 这一笔要排最上面，而且刷红 */
  { id: "pay-1", studySiteId: "s1", siteCode: "SS-01", subjectId: "u1",
    screeningNo: "S-0203", visitId: "v1", visitLabel: "C3D1 给药",
    amountCents: 60000, dueOn: day(-48), paidOn: null, receiptRef: null, ageDays: 48 },
  { id: "pay-2", studySiteId: "s1", siteCode: "SS-01", subjectId: "u-102",
    screeningNo: "SS-01-P0102", visitId: "v-102", visitLabel: "筛选期评估",
    amountCents: 30000, dueOn: day(-6), paidOn: null, receiptRef: null, ageDays: 6 },
  /* **发了但没凭证** —— 比"还没发"更麻烦，关闭中心那天对不上 */
  { id: "pay-3", studySiteId: "s2", siteCode: "SS-07", subjectId: "u2",
    screeningNo: "S-0331", visitId: "v3", visitLabel: "C2D1 给药",
    amountCents: 60000, dueOn: day(-30), paidOn: day(-22), receiptRef: null, ageDays: 30 },
  { id: "pay-4", studySiteId: "s2", siteCode: "SS-07", subjectId: "u2",
    screeningNo: "S-0331", visitId: null, visitLabel: null,
    amountCents: 45000, dueOn: day(-60), paidOn: day(-58), receiptRef: "RC-2026-0088",
    ageDays: 60 }
];

export const mkSubmissions = (): MockSubmission[] => [
  { id: "sub-1", studySiteId: "s1", kind: "initial", submittedOn: day(-300),
    decision: "approved", decidedOn: day(-280), refNo: "PJ-2025-118", note: null },
  /* 递上去 74 天没动静 —— 这一条要刷红，而不是和刚递的那份同色 */
  { id: "sub-2", studySiteId: "s1", kind: "amendment", submittedOn: day(-74),
    decision: "pending", decidedOn: null, refNo: "PJ-2026-041",
    note: "方案 v3.1，新增一次影像评估" },
  { id: "sub-3", studySiteId: "s2", kind: "initial", submittedOn: day(-210),
    decision: "approved", decidedOn: day(-195), refNo: "ZS-2025-233", note: null },
  { id: "sub-4", studySiteId: "s2", kind: "annual", submittedOn: day(-12),
    decision: "pending", decidedOn: null, refNo: null, note: "年度跟踪审查" }
];

/* 样本：三种结局各一，因为这一页要分的正是这三种 ——
     在途 21 天（久到该去问）、在途 3 天（正常）、已收到（闭环）、还没寄。
   全给"已收到"的话，"寄出了但没确认"那条红条永远不出现，
   而它是这一页存在的理由。 */
function makeSpecimens(): Scenario["specimens"] {
  const d = (n: number) => new Date(Date.now() - n * 86_400_000).toISOString().slice(0, 10);
  return [
    { id: "sp-1", studySiteId: "s1", subjectRef: "R-0203", kind: "全血",
      collectedOn: d(24), shippedOn: d(21), receivedOn: null, discardedOn: null,
      trackingNo: "SF-77301", closed: false },
    { id: "sp-2", studySiteId: "s1", subjectRef: "R-0203", kind: "血清",
      collectedOn: d(5), shippedOn: d(3), receivedOn: null, discardedOn: null,
      trackingNo: "SF-77455", closed: false },
    { id: "sp-3", studySiteId: "s1", subjectRef: "S-0102", kind: "尿",
      collectedOn: d(30), shippedOn: d(28), receivedOn: d(26), discardedOn: null,
      trackingNo: "SF-77120", closed: true },
    { id: "sp-4", studySiteId: "s2", subjectRef: "R-0331", kind: "全血",
      collectedOn: d(1), shippedOn: null, receivedOn: null, discardedOn: null,
      trackingNo: null, closed: false }
  ];
}
