/* ════════════════════════════════════════════════════════════════════
   一条业务流的 mock 场景 —— **有状态的，不是一堆固定响应。**

   契约生成的 examples.json 覆盖面全，但每个响应各自随机，
   拼不成一条连贯的流程：勾掉的任务下一次请求又是未勾的，
   完成访视后不会真的排出下一次。那种 mock 能验证「页面画得出来」，
   验证不了「这条流程走得通」—— 而后者才是 Phase 5 的退出标准。

   所以这里给**一份内存状态**，只覆盖 CRC 每天真正要走的那条路：
   看今天到期的 → 打开一例 → 逐项勾任务 → 完成访视 → 看到一串后果。

   数据取自原型（吴桐 / SS-01 北京协和 / S-0203），与种子同源。
   ════════════════════════════════════════════════════════════════════ */

import {
  DEFAULT_STARTUP_ITEMS, DEFAULT_HANDOVER_ITEMS, STARTUP_CATEGORY_LABEL
} from "@sitedesk/contracts";

export interface MockTask { seq: number; task: string; doneAt: string | null }

export interface MockStartupItem {
  id: string; studySiteId: string; category: string; categoryLabel: string;
  item: string; ownerAccountId: string | null; ownerName: string | null;
  dueOn: string | null; isBlocking: boolean;
  doneAt: string | null; doneByName: string | null; overdueDays: number | null;
}

/** 全量的 TimesheetEntry 形状 —— mock 少几个字段，界面就会在真库上才第一次报错。 */
export interface MockTimesheet {
  id: string; studySiteId: string; siteCode: string;
  accountId: string; personName: string;
  workDate: string; workType: string; workTypeLabel: string;
  billable: boolean; hours: number;
  dayCostCents: number; travelCents: number; costCents: number;
  rateCardId: string;
  subjectId: string | null; visitId: string | null;
  autoGenerated: boolean; note: string | null;
  voidedAt: string | null; voidedByName: string | null; voidReason: string | null;
  createdAt: string;
}

export interface MockRateCard {
  id: string; roleKind: string; level: string | null;
  dayCostCents: number; validFrom: string; validTo: string | null;
  note: string | null;
}

export interface MockHandover {
  id: string; fromAccountId: string; fromName: string;
  toAccountId: string; toName: string; reason: string; plannedOn: string;
  status: string; completedAt: string | null;
  sites: { id: string; code: string; hospital: string }[];
  items: { seq: number; item: string; doneAt: string | null; doneByName: string | null }[];
}

export interface MockVisit {
  id: string; subjectId: string; screeningNo: string;
  studySiteId: string; siteCode: string; seq: number;
  visitCode: string; visitLabel: string;
  targetDate: string; windowDays: number; windowFrom: string; windowTo: string;
  actualDate: string | null; status: string; edcStatus: string;
  edcDaysLate: number | null; outOfWindow: boolean; daysLeft: number | null;
  piConfirmedAt: string | null; piConfirmedByName: string | null;
  tasks: MockTask[];
}

const iso = (d: Date) => d.toISOString().slice(0, 10);
const shift = (base: Date, n: number) => {
  const d = new Date(base); d.setDate(d.getDate() + n); return iso(d);
};
const TODAY = new Date();

const SITES = [
  { id: "s1", code: "SS-01", hospital: "北京协和医院", state: "enrolling" },
  { id: "s2", code: "SS-07", hospital: "中山大学肿瘤防治中心", state: "enrolling" },
  /* 第三个中心停在 contract —— 它存在的唯一理由是让 SIV 闸门有东西可拦。
     两个 enrolling 的中心谁也过不了闸门那一关，因为它们早就过去了。 */
  { id: "s3", code: "SS-14", hospital: "江苏省人民医院", state: "contract" }
];

/** 每例的任务清单来自项目的 SOA —— 与 visit_template_task 同一套文字 */
const TASKS_ONCO = [
  "生命体征与体格检查",
  "血常规 + 生化采血（空腹）",
  "ECOG 体能评分记录",
  "研究药物发放与既往剩余回收清点",
  "合并用药与不良事件问询"
];
const TASKS_IO = [
  "生命体征与体格检查",
  "采血与样本离心送检（2 小时内）",
  "免疫相关不良事件专项问询",
  "研究药物配制核对与输注陪同"
];

function mkVisit(
  id: string, site: typeof SITES[number], screeningNo: string, subjectId: string,
  seq: number, label: string, dueIn: number, win: number, tasks: string[],
  doneCount = 0
): MockVisit {
  const target = shift(TODAY, dueIn);
  return {
    id, subjectId, screeningNo, studySiteId: site.id, siteCode: site.code, seq,
    visitCode: `V-${seq}`, visitLabel: label,
    targetDate: target, windowDays: win,
    windowFrom: shift(new Date(target), -win), windowTo: shift(new Date(target), win),
    actualDate: null, status: "planned", edcStatus: "pending",
    edcDaysLate: null, outOfWindow: dueIn + win < 0, daysLeft: dueIn + win,
    piConfirmedAt: null, piConfirmedByName: null,
    tasks: tasks.map((t, i) => ({
      seq: i, task: t, doneAt: i < doneCount ? new Date().toISOString() : null }))
  };
}

/** 可变状态。每次 resetScenario() 回到已知起点 —— 测试要从确定处出发。 */
export interface Scenario {
  visits: MockVisit[];
  /** 中心的当前阶段。推进会改它，所以不能从 SITES 常量上读。 */
  siteState: Record<string, string>;
  /** 计划 SIV 日 —— 清单项的到期日全是相对它算的，两处必须同源 */
  sivPlannedOn: string;
  /** 推进到 siv / enrolling 时回填，与后端的 `coalesce(siv_on, CURRENT_DATE)` 同义 */
  sivOn: Record<string, string>;
  fpiOn: Record<string, string>;
  startupItems: MockStartupItem[];
  handovers: MockHandover[];
  /** 完成访视时累积产生的质量事件，供台账页读取 */
  qualityEvents: {
    id: string; code: string; siteCode: string; kind: string; severity: string;
    state: string; title: string; detail: string; autoGenerated: boolean;
    raisedBy: string; raisedOn: string; ageDays: number;
    /* SAE 三件套（I6）。只有 kind='sae' 的那几条有值。 */
    studySiteId?: string;
    occurredAt?: string | null; reportedAt?: string | null;
    sourceEventId?: string | null;
  }[];
  /** 药品流水（I5）。在手数量是**算出来的**，所以这里不存那个数。 */
  ipMovements: {
    id: string; studySiteId: string; movedOn: string; kind: string;
    quantity: number; subjectRef: string | null; refNo: string | null; note: string | null;
  }[];
  timesheets: MockTimesheet[];
  rateCards: MockRateCard[];
}

export function makeScenario(): Scenario {
  return {
    visits: [
      /* 已超窗 3 天 —— 列表第一屏就该看见它 */
      mkVisit("v1", SITES[0]!, "S-0331", "u1", 4, "C4D1 第 4 周期给药",
        -6, 3, TASKS_ONCO, 2),
      /* 今天到期 */
      mkVisit("v2", SITES[0]!, "S-0203", "u2", 8, "C8D1 第 8 周期给药",
        0, 3, TASKS_ONCO, 3),
      /* 窗口内，还有 2 天 */
      mkVisit("v3", SITES[1]!, "S-0224", "u3", 3, "C3D1 给药 + 肿瘤评估",
        2, 2, TASKS_IO, 0),
      /* 下周 */
      mkVisit("v4", SITES[1]!, "S-0198", "u4", 12, "C12D1 第 12 周期给药",
        7, 3, TASKS_IO, 0)
    ],
    /* 演示数据里**故意各摆一条**：一条按时上报、一条超时未报。
       只摆按时的那种，界面上那两个"最坏的一条""还在计时"永远画不出来，
       于是没有人会发现它们其实没写对。 */
    qualityEvents: makeSaes(),
    ipMovements: makeIpMovements(),
    timesheets: makeTimesheets(),
    rateCards: makeRateCards(),
    siteState: Object.fromEntries(SITES.map(s => [s.id, s.state])),
    sivPlannedOn: SIV_PLANNED,
    sivOn: {}, fpiOn: {},
    startupItems: makeStartupItems("s3"),
    handovers: [makeHandover()]
  };
}

/** 启动清单由**契约里的标准清单**铺开，不另写一份。
 *  另写一份的代价不是重复，是分歧：真实建档铺 16 项、mock 铺 6 项，
 *  于是 mock 上走得通的流程在真库上多出十项没人见过的阻塞。 */
const SIV_PLANNED = shift(TODAY, 20);

function makeStartupItems(siteId: string): MockStartupItem[] {
  return DEFAULT_STARTUP_ITEMS.map((d, i) => {
    const due = shift(new Date(SIV_PLANNED), d.dueOffset);
    const overdue = Math.round(
      (TODAY.getTime() - new Date(due).getTime()) / 86_400_000);
    return {
      id: `si-${i}`, studySiteId: siteId,
      category: d.category, categoryLabel: STARTUP_CATEGORY_LABEL[d.category],
      item: d.item, ownerAccountId: "a-wutong", ownerName: "吴桐",
      dueOn: due, isBlocking: d.blocking,
      doneAt: null, doneByName: null,
      overdueDays: overdue > 0 ? overdue : null
    };
  });
}

function makeHandover(): MockHandover {
  return {
    id: "h1", fromAccountId: "a-wutong", fromName: "吴桐",
    toAccountId: "a-tangyan", toName: "唐延",
    reason: "产假，为期六个月", plannedOn: shift(TODAY, 7),
    status: "pending", completedAt: null,
    sites: [{ id: "s1", code: "SS-01", hospital: "北京协和医院" }],
    items: DEFAULT_HANDOVER_ITEMS.map((item, seq) => ({
      seq, item, doneAt: null, doneByName: null
    }))
  };
}

/** mock 人员名册。发起交接的表单要靠它把候选人缩到同工种。 */
export const STAFF_LIST = [
  { accountId: "a-wutong",  login: "wutong",  displayName: "吴桐", roleKind: "CRC",
    level: "P4", city: "北京", gcpExpiresOn: null, gcpDaysLeft: null,
    mentorName: null, successorName: null, siteCount: 2, successionGap: false },
  { accountId: "a-tangyan", login: "tangyan", displayName: "唐延", roleKind: "CRC",
    level: "P3", city: "西安", gcpExpiresOn: null, gcpDaysLeft: null,
    mentorName: "吴桐", successorName: null, siteCount: 1, successionGap: false },
  { accountId: "a-duan",    login: "duanzhiyu", displayName: "段志远", roleKind: "CRA",
    level: "P5", city: "上海", gcpExpiresOn: null, gcpDaysLeft: null,
    mentorName: null, successorName: null, siteCount: 4, successionGap: true }
];

/** 工作类型 → 中文名与是否可计费。与库里的 work_type 表同一套口径：
 *  billable 由类型推导，提交时**落库固化**（I1）—— 所以 mock 也必须
 *  在创建那一刻把它定下来，而不是渲染时再查表。 */
export const WORK_TYPE_META: Record<string, { label: string; billable: boolean }> = {
  visit_support: { label: "受试者访视陪同", billable: true },
  sdv:           { label: "源数据准备与核对", billable: true },
  ethics:        { label: "伦理递交与跟进", billable: true },
  monitoring:    { label: "现场监查（IMV）", billable: true },
  ip_mgmt:       { label: "药品与物资管理", billable: true },
  training:      { label: "内部培训", billable: false },
  bd:            { label: "投标与商务支持", billable: false },
  rework:        { label: "返工与整改", billable: false }
};

/** 现行费率卡：CRC 通用 1180 元/人天。第二张已收口，用来演示"调价是两步"。 */
function makeRateCards(): MockRateCard[] {
  return [
    { id: "rc-crc-2026", roleKind: "CRC", level: null, dayCostCents: 118000,
      validFrom: "2026-01-01", validTo: null, note: "2026 年度" },
    { id: "rc-crc-2025", roleKind: "CRC", level: null, dayCostCents: 106000,
      validFrom: "2025-01-01", validTo: "2025-12-31", note: "2025 年度（已收口）" },
    { id: "rc-cra-2026", roleKind: "CRA", level: null, dayCostCents: 129800,
      validFrom: "2026-01-01", validTo: null, note: "2026 年度" }
  ];
}

const DAY_COST = 118000;
/** 与 calc 的 entryCostCents 同一个式子 —— mock 里也不另立口径。 */
const cost = (hours: number, travel = 0) =>
  Math.round((hours / 8) * DAY_COST) + travel;

export function mkTimesheet(
  id: string, site: typeof SITES[number], workDate: string, workType: string,
  hours: number, opts: { travel?: number; auto?: boolean; note?: string } = {}
): MockTimesheet {
  const meta = WORK_TYPE_META[workType]!;
  const travel = opts.travel ?? 0;
  return {
    id, studySiteId: site.id, siteCode: site.code,
    accountId: "a-wutong", personName: "吴桐",
    workDate, workType, workTypeLabel: meta.label, billable: meta.billable,
    hours, dayCostCents: DAY_COST, travelCents: travel,
    costCents: cost(hours, travel), rateCardId: "rc-crc-2026",
    subjectId: null, visitId: null,
    autoGenerated: opts.auto ?? false, note: opts.note ?? null,
    voidedAt: null, voidedByName: null, voidReason: null,
    createdAt: new Date().toISOString()
  };
}

function makeTimesheets(): MockTimesheet[] {
  return [
    mkTimesheet("ts-1", SITES[0]!, shift(TODAY, -1), "visit_support", 3.5,
      { travel: 8600, note: "S-0203 C8D1 陪同" }),
    mkTimesheet("ts-2", SITES[0]!, shift(TODAY, -2), "sdv", 5),
    /* 不可计费的那一条：占比高说明人力花在了卖不出去的事情上 */
    mkTimesheet("ts-3", SITES[1]!, shift(TODAY, -3), "training", 2)
  ];
}

export const SITE_BY_ID = Object.fromEntries(SITES.map(s => [s.id, s]));
export const SITES_LIST = SITES;


/* ── SAE 与药品：演示数据 ───────────────────────────────────────────
   都挂在 SITES[0]（s1）上。数字刻意不圆整 ——
   "24.0 小时"看起来像占位符，"31.5 小时"看起来像真的发生过。 */
const hoursAgo = (h: number) => new Date(TODAY.getTime() - h * 3_600_000).toISOString();

function makeSaes(): Scenario["qualityEvents"] {
  const site = SITES[0]!;
  const base = {
    siteCode: site.code, studySiteId: site.id, kind: "sae", severity: "critical",
    state: "open", autoGenerated: false, raisedBy: "cra", ageDays: 2,
    sourceEventId: null
  };
  return [
    { ...base, id: "sae1", code: "SAE-DEMO01",
      title: "受试者出现 III 度中性粒细胞减少",
      detail: "住院对症治疗，研究者判定与试验药物可能相关。",
      raisedOn: hoursAgo(31.5).slice(0, 10),
      occurredAt: hoursAgo(31.5), reportedAt: hoursAgo(23) },   // 8.5 小时，按时
    { ...base, id: "sae2", code: "SAE-DEMO02",
      title: "受试者因肝功能异常住院",
      detail: "尚在整理上报材料 —— 已经超过 24 小时。",
      raisedOn: hoursAgo(52).slice(0, 10),
      occurredAt: hoursAgo(52), reportedAt: null }              // 52 小时未报 = 迟报
  ];
}

function makeIpMovements(): Scenario["ipMovements"] {
  const site = SITES[0]!;
  const on = (d: number) => shift(TODAY, d);
  const m = (id: string, kind: string, quantity: number,
             extra: Partial<Scenario["ipMovements"][number]> = {}) => ({
    id, studySiteId: site.id, movedOn: on(-30), kind, quantity,
    subjectRef: null, refNo: null, note: null, ...extra
  });
  /* 30 收 − 12 发 = 18 在手：关闭闸门会拦下它，而台账上说得出为什么。 */
  return [
    m("ip1", "receipt", 30, { refNo: "SF-2026-0011" }),
    m("ip2", "dispense", 12, { movedOn: on(-14), subjectRef: "S-0331" })
  ];
}
